/* ========================================================================= */
/*  ASGARD-5877 Polymorphic C/C++ Obfuscation & Hardening Macro Header       */
/*  Auto-generated by Random_vISA / ASGARD-5877 Macro Obfuscation Engine     */
/* ========================================================================= */
#ifndef _ASGARD_OBF_H_
#define _ASGARD_OBF_H_

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#ifndef __cplusplus
  #include <stdbool.h>
#endif

#if defined(__GNUC__) || defined(__clang__)
  #define ASG_INLINE __attribute__((always_inline)) inline
#elif defined(_MSC_VER)
  #define ASG_INLINE __forceinline
#else
  #define ASG_INLINE inline
#endif

/* 1. STACK STRING ENCRYPTION (Alloca / Compound Literal Decryption)         */
static ASG_INLINE char* ASG_decrypt_str(char* buf, const uint8_t* enc, size_t len, uint32_t key) {
    volatile uint32_t vkey = key;
    volatile const uint8_t* venc = enc;
    for (size_t i = 0; i < len; ++i) {
        uint8_t k = (uint8_t)((vkey ^ (uint32_t)(i * 0x5DU)) & 0xFFU);
        buf[i] = (char)(venc[i] ^ k);
    }
    buf[len] = '\0';
    return buf;
}
#if defined(__cplusplus)
#define ASG_STR(enc_bytes, len, key) \
    ASG_decrypt_str((char*)__builtin_alloca((len) + 1), (const uint8_t*)(enc_bytes), (len), (key))
#elif defined(__GNUC__) || defined(__clang__)
#define ASG_STR(enc_bytes, len, key) ({ \
    static const uint8_t _enc[] = enc_bytes; \
    char* _buf = (char*)__builtin_alloca((len) + 1); \
    volatile uint32_t _vkey = (uint32_t)(key); \
    volatile const uint8_t* _venc = _enc; \
    for (size_t _i = 0; _i < (size_t)(len); ++_i) { \
        uint8_t _k = (uint8_t)((_vkey ^ (uint32_t)(_i * 0x5DU)) & 0xFFU); \
        _buf[_i] = (char)(_venc[_i] ^ _k); \
    } \
    _buf[len] = '\0'; \
    __asm__ volatile("" : "+r"(_buf) : : "memory"); \
    _buf; \
})
#else
#define ASG_STR(enc_bytes, len, key) \
    ASG_decrypt_str((char*)alloca((len) + 1), (const uint8_t*)(enc_bytes), (len), (key))
#endif

/* ------------------------------------------------------------------------- */
/* 2. MIXED BOOLEAN-ARITHMETIC (MBA) MACROS (Zhou / Eyrolles Identities)     */
/* ------------------------------------------------------------------------- */
/* Addition: x + y = (x ^ y) + 2*(x & y) */
#define ASG_MBA_ADD(a, b) (((a) ^ (b)) + 2 * ((a) & (b)))

/* Subtraction: x - y = (x ^ y) - 2*(~x & y) */
#define ASG_MBA_SUB(a, b) (((a) ^ (b)) - 2 * ((~(a)) & (b)))

/* Bitwise XOR: x ^ y = (x | y) - (x & y) */
#define ASG_MBA_XOR(a, b) (((a) | (b)) - ((a) & (b)))

/* Bitwise AND: x y = (x + y) - (x | y) */
#define ASG_MBA_AND(a, b) (((a) + (b)) - ((a) | (b)))

/* Bitwise OR: x | y = (x ^ y) + (x & y) */
#define ASG_MBA_OR(a, b) (((a) ^ (b)) + ((a) & (b)))

/* Bitwise NOT: ~x = x ^ 0xFFFFFFFFFFFFFFFFULL */
#define ASG_MBA_NOT(a) ((a) ^ 0xFFFFFFFFFFFFFFFFULL)

/* Level 2 Nested MBA: x + y expanded through XOR and AND identities */
#define ASG_MBA_ADD_L2(a, b) (ASG_MBA_XOR((a), (b)) + 2 * ASG_MBA_AND((a), (b)))
#define ASG_MBA_SUB_L2(a, b) (ASG_MBA_XOR((a), (b)) - 2 * ASG_MBA_AND(ASG_MBA_NOT(a), (b)))

/* Non-Linear MBA (NLMBA): Non-linear cross-product expansion resisting 1-bit linear solvers (SiMBA/GAMBA) */
#define ASG_NLMBA_MUL(a, b) ((((a) & (b)) * ((a) | (b))) + (((a) & (~(b))) * ((~(a)) & (b))))
#define ASG_ZERO_INV1(a, b) ((((a) | (b)) + ((a) & (b))) - ((a) + (b)))
#define ASG_ZERO_INV2(a, b) (((a) ^ (b)) - (((a) | (b)) - ((a) & (b))))
#define ASG_ZERO_INV3(a, b) ((((a) & (b)) + ((a) & (~(b)))) - (a))

/* ------------------------------------------------------------------------- */
/* 3. CONSTANT BLINDING MACROS                                              */
/* ------------------------------------------------------------------------- */
#define ASG_BLIND_U64(c1, k1, k2) ((((uint64_t)(c1) ^ (uint64_t)(k1)) + (uint64_t)(k2)) - (uint64_t)(k2))
#define ASG_BLIND_I64(c1, k1, k2) ((int64_t)ASG_BLIND_U64(c1, k1, k2))
#define ASG_BLIND_I32(c1, k1, k2) ((int32_t)ASG_BLIND_U64(c1, k1, k2))

/* ------------------------------------------------------------------------- */
/* 4. NUMBER-THEORETIC OPAQUE PREDICATES                                    */
/* Invariants: for all x in Z, x*(x+1) % 2 == 0 and x^2 + x + 7 % 2 != 0    */
/* ------------------------------------------------------------------------- */
#define ASG_OPAQUE_TRUE(x)  (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) == 0ULL)
#define ASG_OPAQUE_FALSE(x) (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) != 0ULL)
#define ASG_IF_OPAQUE(x, true_body, false_body) do { \
    if (ASG_OPAQUE_TRUE(x)) { true_body; } else { false_body; } \
} while(0)

/* ------------------------------------------------------------------------- */
/* 5. CONTROL-FLOW FLATTENING (CFF) PREPROCESSOR DSL                        */
/* ------------------------------------------------------------------------- */
#define ASG_CFF_BEGIN(state_var, init_state) \
    uint32_t state_var = (init_state); \
    while (state_var != 0U) { \
        switch (state_var) {

#define ASG_CFF_STATE(state_id) case (state_id):

#define ASG_CFF_NEXT(state_var, next_state) do { \
    state_var = (next_state); \
} while(0); break

#define ASG_CFF_EXIT(state_var) do { \
    state_var = 0U; \
} while(0); break

#define ASG_CFF_END() \
        default: \
            state_var = 0U; \
            break; \
        } \
    }

/* ------------------------------------------------------------------------- */
/* 6. MARKER-BASED REGION PROTECTION (VMProtect Style SDK)                   */
/* ------------------------------------------------------------------------- */
#if defined(__GNUC__) || defined(__clang__)
  #if defined(__arm64__) || defined(__aarch64__)
    #define ASGARD_BEGIN_VIRTUALIZE(tag) \
        __asm__ volatile ("b 1f \n\t .ascii \"ASGARD_BEG_V____\" \n\t .balign 4 \n 1:\n\t")
    #define ASGARD_BEGIN_MUTATION(tag) \
        __asm__ volatile ("b 1f \n\t .ascii \"ASGARD_BEG_M____\" \n\t .balign 4 \n 1:\n\t")
    #define ASGARD_BEGIN_ULTRA(tag) \
        __asm__ volatile ("b 1f \n\t .ascii \"ASGARD_BEG_U____\" \n\t .balign 4 \n 1:\n\t")
    #define ASGARD_END() \
        __asm__ volatile ("b 1f \n\t .ascii \"ASGARD_END______\" \n\t .balign 4 \n 1:\n\t")
  #else
    #define ASGARD_BEGIN_VIRTUALIZE(tag) \
        __asm__ volatile ("jmp 1f \n\t .ascii \"ASGARD_BEG_V__\" \n 1:\n\t")
    #define ASGARD_BEGIN_MUTATION(tag) \
        __asm__ volatile ("jmp 1f \n\t .ascii \"ASGARD_BEG_M__\" \n 1:\n\t")
    #define ASGARD_BEGIN_ULTRA(tag) \
        __asm__ volatile ("jmp 1f \n\t .ascii \"ASGARD_BEG_U__\" \n 1:\n\t")
    #define ASGARD_END() \
        __asm__ volatile ("jmp 1f \n\t .ascii \"ASGARD_END____\" \n 1:\n\t")
  #endif
#else
  #define ASGARD_BEGIN_VIRTUALIZE(tag)
  #define ASGARD_BEGIN_MUTATION(tag)
  #define ASGARD_BEGIN_ULTRA(tag)
  #define ASGARD_END()
#endif

/* ------------------------------------------------------------------------- */
/* 11. MULTITHREADED NANOMITES & TRAP-AND-TRACE DISPATCHING                  */
/* ------------------------------------------------------------------------- */
typedef struct {
    uint32_t trap_id;
    uintptr_t target_true;
    uintptr_t target_false;
    uint32_t key;
} ASG_nanomite_entry_t;

static ASG_nanomite_entry_t ASG_nanomite_table[64];
static size_t ASG_nanomite_count = 0;
static volatile uint32_t ASG_current_trap_id = 0;
static volatile uint32_t ASG_current_condition = 0;

static inline void ASG_register_nanomite(uint32_t trap_id, uintptr_t t_true, uintptr_t t_false, uint32_t key) {
    if (ASG_nanomite_count < 64) {
        ASG_nanomite_table[ASG_nanomite_count].trap_id = trap_id;
        ASG_nanomite_table[ASG_nanomite_count].target_true = t_true ^ (uintptr_t)key;
        ASG_nanomite_table[ASG_nanomite_count].target_false = t_false ^ (uintptr_t)key;
        ASG_nanomite_table[ASG_nanomite_count].key = key;
        ASG_nanomite_count++;
    }
}

#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)
#include <signal.h>
#if defined(__APPLE__)
#include <sys/ucontext.h>
#else
#include <ucontext.h>
#endif
static void ASG_nanomite_trap_handler(int sig, siginfo_t* info, void* ucontext_ptr) {
    (void)sig; (void)info;
    ucontext_t* uc = (ucontext_t*)ucontext_ptr;
    for (size_t i = 0; i < ASG_nanomite_count; ++i) {
        if (ASG_nanomite_table[i].trap_id == ASG_current_trap_id) {
            uintptr_t enc_target = ASG_current_condition ?
                ASG_nanomite_table[i].target_true :
                ASG_nanomite_table[i].target_false;
            uintptr_t real_target = enc_target ^ (uintptr_t)ASG_nanomite_table[i].key;
#if defined(__APPLE__)
#if defined(__x86_64__)
            uc->uc_mcontext->__ss.__rip = real_target;
#elif defined(__arm64__) || defined(__aarch64__)
            uc->uc_mcontext->__ss.__pc = real_target;
#endif
#elif defined(__linux__)
#if defined(__x86_64__)
            uc->uc_mcontext.gregs[REG_RIP] = (greg_t)real_target;
#elif defined(__arm64__) || defined(__aarch64__)
            uc->uc_mcontext.pc = real_target;
#endif
#endif
            ASG_current_trap_id = 0;
            return;
        }
    }
}

static inline void ASG_install_nanomites(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = ASG_nanomite_trap_handler;
    sa.sa_flags = SA_SIGINFO;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGTRAP, &sa, NULL);
}

#define ASG_NANOMITE_INIT() ASG_install_nanomites()
#define ASG_NANOMITE_REGISTER(id, t_true, t_false, key) ASG_register_nanomite((id), (uintptr_t)(t_true), (uintptr_t)(t_false), (uint32_t)(key))
#define ASG_NANOMITE_DISPATCH(id, cond) do { \
    ASG_current_trap_id = (id); \
    ASG_current_condition = (cond) ? 1 : 0; \
    raise(SIGTRAP); \
} while(0)
#elif defined(_WIN32) || defined(_WIN64)
static LONG WINAPI ASG_nanomite_veh_handler(PEXCEPTION_POINTERS pExceptionInfo) {
    if (pExceptionInfo->ExceptionRecord->ExceptionCode == EXCEPTION_BREAKPOINT || pExceptionInfo->ExceptionRecord->ExceptionCode == 0xE0000002) {
        for (size_t i = 0; i < ASG_nanomite_count; ++i) {
            if (ASG_nanomite_table[i].trap_id == ASG_current_trap_id) {
                uintptr_t enc_target = ASG_current_condition ?
                    ASG_nanomite_table[i].target_true :
                    ASG_nanomite_table[i].target_false;
                uintptr_t real_target = enc_target ^ (uintptr_t)ASG_nanomite_table[i].key;
#if defined(_M_X64) || defined(__x86_64__)
                pExceptionInfo->ContextRecord->Rip = (DWORD64)real_target;
#else
                pExceptionInfo->ContextRecord->Eip = (DWORD)real_target;
#endif
                ASG_current_trap_id = 0;
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }
    }
    return EXCEPTION_CONTINUE_SEARCH;
}

static inline void ASG_install_nanomites(void) {
    AddVectoredExceptionHandler(1, ASG_nanomite_veh_handler);
}

#define ASG_NANOMITE_INIT() ASG_install_nanomites()
#define ASG_NANOMITE_REGISTER(id, t_true, t_false, key) ASG_register_nanomite((id), (uintptr_t)(t_true), (uintptr_t)(t_false), (uint32_t)(key))
#define ASG_NANOMITE_DISPATCH(id, cond) do { \
    ASG_current_trap_id = (id); \
    ASG_current_condition = (cond) ? 1 : 0; \
    RaiseException(0xE0000002, 0, 0, NULL); \
} while(0)
#else
#define ASG_NANOMITE_INIT() ((void)0)
#define ASG_NANOMITE_REGISTER(id, t_true, t_false, key) ((void)0)
#define ASG_NANOMITE_DISPATCH(id, cond) ((void)0)
#endif

#endif /* _ASGARD_OBF_H_ */
