(** C_macro_obf — C/C++ Preprocessor & Source-Level Macro Obfuscation Engine. *)

type config = {
  seed : int;
  mba_depth : int;
  obfuscate_strings : bool;
  obfuscate_constants : bool;
  obfuscate_arithmetic : bool;
  inject_opaque_predicates : bool;
  api_hashing : bool;
  anti_debug : bool;
  signal_dispatch : bool;
  timing_guard : bool;
  timing_threshold_ticks : int64;
  macro_prefix : string;
}

let default_config = {
  seed = 42;
  mba_depth = 2;
  obfuscate_strings = true;
  obfuscate_constants = true;
  obfuscate_arithmetic = true;
  inject_opaque_predicates = true;
  api_hashing = true;
  anti_debug = true;
  signal_dispatch = true;
  timing_guard = true;
  timing_threshold_ticks = 50000000L;
  macro_prefix = "ASG_";
}

let xorshift32 seed =
  let x = ref (if seed = 0 then 0x1337BEEF else seed land 0x7FFFFFFF) in
  x := !x lxor (!x lsl 13);
  x := !x lxor (!x lsr 17);
  x := !x lxor (!x lsl 5);
  let res = !x land 0x7FFFFFFF in
  if res = 0 then 0x5A5A5A5A else res

let rand_u64 rng =
  let hi = Random.State.int64 rng 0x100000000L in
  let lo = Random.State.int64 rng 0x100000000L in
  Int64.logor (Int64.shift_left hi 32) lo

(** Generate standalone C/C++ header [asgard_obf.h] *)
let generate_header ?(config = default_config) () =
  let p = config.macro_prefix in
  let rng = Random.State.make [| config.seed |] in
  let _ = rng in
  let b = Buffer.create 4096 in
  let add s = Buffer.add_string b (s ^ "\n") in

  add "/* ========================================================================= */";
  add "/*  ASGARD-5877 Polymorphic C/C++ Obfuscation & Hardening Macro Header       */";
  add "/*  Auto-generated by Random_vISA / ASGARD-5877 Macro Obfuscation Engine     */";
  add "/* ========================================================================= */";
  add "#ifndef _ASGARD_OBF_H_";
  add "#define _ASGARD_OBF_H_";
  add "";
  add "#include <stdint.h>";
  add "#include <stddef.h>";
  add "#include <stdlib.h>";
  add "#include <string.h>";
  add "#ifndef __cplusplus";
  add "  #include <stdbool.h>";
  add "#endif";
  add "";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add ("  #define " ^ p ^ "INLINE __attribute__((always_inline)) inline");
  add "#elif defined(_MSC_VER)";
  add ("  #define " ^ p ^ "INLINE __forceinline");
  add "#else";
  add ("  #define " ^ p ^ "INLINE inline");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 1. STACK STRING ENCRYPTION (Alloca / Compound Literal Decryption)         */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add ("#define " ^ p ^ "STR(enc_bytes, len, key) ({ \\");
  add "    static const uint8_t _enc[] = enc_bytes; \\";
  add "    char* _buf = (char*)__builtin_alloca((len) + 1); \\";
  add "    volatile uint32_t _vkey = (uint32_t)(key); \\";
  add "    volatile const uint8_t* _venc = _enc; \\";
  add "    for (size_t _i = 0; _i < (size_t)(len); ++_i) { \\";
  add "        uint8_t _k = (uint8_t)((_vkey ^ (uint32_t)(_i * 0x5DU)) & 0xFFU); \\";
  add "        _buf[_i] = (char)(_venc[_i] ^ _k); \\";
  add "    } \\";
  add "    _buf[len] = '\\0'; \\";
  add "    __asm__ volatile(\"\" : \"+r\"(_buf) : : \"memory\"); \\";
  add "    _buf; \\";
  add "})";

  add "#else";
  add ("static " ^ p ^ "INLINE char* " ^ p ^ "decrypt_str(char* buf, const uint8_t* enc, size_t len, uint32_t key) {");
  add "    volatile uint32_t vkey = key;";
  add "    volatile const uint8_t* venc = enc;";
  add "    for (size_t i = 0; i < len; ++i) {";
  add "        uint8_t k = (uint8_t)((vkey ^ (uint32_t)(i * 0x5DU)) & 0xFFU);";
  add "        buf[i] = (char)(venc[i] ^ k);";
  add "    }";
  add "    buf[len] = '\\0';";
  add "    return buf;";
  add "}";
  add ("#define " ^ p ^ "STR(enc_bytes, len, key) \\");
  add ("    " ^ p ^ "decrypt_str((char*)alloca((len) + 1), (const uint8_t*)(enc_bytes), (len), (key))");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 2. MIXED BOOLEAN-ARITHMETIC (MBA) MACROS (Zhou / Eyrolles Identities)     */";
  add "/* ------------------------------------------------------------------------- */";
  add "/* Addition: x + y = (x ^ y) + 2*(x & y) */";
  add ("#define " ^ p ^ "MBA_ADD(a, b) (((a) ^ (b)) + 2 * ((a) & (b)))");
  add "";
  add "/* Subtraction: x - y = (x ^ y) - 2*(~x & y) */";
  add ("#define " ^ p ^ "MBA_SUB(a, b) (((a) ^ (b)) - 2 * ((~(a)) & (b)))");
  add "";
  add "/* Bitwise XOR: x ^ y = (x | y) - (x & y) */";
  add ("#define " ^ p ^ "MBA_XOR(a, b) (((a) | (b)) - ((a) & (b)))");
  add "";
  add "/* Bitwise AND: x & y = (x + y) - (x | y) */";
  add ("#define " ^ p ^ "MBA_AND(a, b) (((a) + (b)) - ((a) | (b)))");
  add "";
  add "/* Bitwise OR: x | y = (x ^ y) + (x & y) */";
  add ("#define " ^ p ^ "MBA_OR(a, b) (((a) ^ (b)) + ((a) & (b)))");
  add "";
  add "/* Bitwise NOT: ~x = x ^ 0xFFFFFFFFFFFFFFFFULL */";
  add ("#define " ^ p ^ "MBA_NOT(a) ((a) ^ 0xFFFFFFFFFFFFFFFFULL)");
  add "";
  add "/* Level 2 Nested MBA: x + y expanded through XOR and AND identities */";
  add ("#define " ^ p ^ "MBA_ADD_L2(a, b) (" ^ p ^ "MBA_XOR((a), (b)) + 2 * " ^ p ^ "MBA_AND((a), (b)))");
  add ("#define " ^ p ^ "MBA_SUB_L2(a, b) (" ^ p ^ "MBA_XOR((a), (b)) - 2 * " ^ p ^ "MBA_AND(" ^ p ^ "MBA_NOT(a), (b)))");
  add "";
  add "/* Non-Linear MBA (NLMBA): Non-linear cross-product expansion resisting 1-bit linear solvers (SiMBA/GAMBA) */";
  add ("#define " ^ p ^ "NLMBA_MUL(a, b) ((((a) & (b)) * ((a) | (b))) + (((a) & (~(b))) * ((~(a)) & (b))))");
  add ("#define " ^ p ^ "ZERO_INV1(a, b) ((((a) | (b)) + ((a) & (b))) - ((a) + (b)))");
  add ("#define " ^ p ^ "ZERO_INV2(a, b) (((a) ^ (b)) - (((a) | (b)) - ((a) & (b))))");
  add ("#define " ^ p ^ "ZERO_INV3(a, b) ((((a) & (b)) + ((a) & (~(b)))) - (a))");

  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 3. CONSTANT BLINDING MACROS                                              */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "BLIND_U64(c1, k1, k2) ((((uint64_t)(c1) ^ (uint64_t)(k1)) + (uint64_t)(k2)) - (uint64_t)(k2))");
  add ("#define " ^ p ^ "BLIND_I64(c1, k1, k2) ((int64_t)" ^ p ^ "BLIND_U64(c1, k1, k2))");
  add ("#define " ^ p ^ "BLIND_I32(c1, k1, k2) ((int32_t)" ^ p ^ "BLIND_U64(c1, k1, k2))");
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 4. NUMBER-THEORETIC OPAQUE PREDICATES                                    */";
  add "/* Invariants: for all x in Z, x*(x+1) % 2 == 0 and x^2 + x + 7 % 2 != 0    */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "OPAQUE_TRUE(x)  (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) == 0ULL)");
  add ("#define " ^ p ^ "OPAQUE_FALSE(x) (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) != 0ULL)");
  add ("#define " ^ p ^ "IF_OPAQUE(x, true_body, false_body) do { \\");
  add ("    if (" ^ p ^ "OPAQUE_TRUE(x)) { true_body; } else { false_body; } \\");
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 5. CONTROL-FLOW FLATTENING (CFF) PREPROCESSOR DSL                        */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "CFF_BEGIN(state_var, init_state) \\");
  add "    uint32_t state_var = (init_state); \\";
  add "    while (state_var != 0U) { \\";
  add "        switch (state_var) {";
  add "";
  add ("#define " ^ p ^ "CFF_STATE(state_id) case (state_id):");
  add "";
  add ("#define " ^ p ^ "CFF_NEXT(state_var, next_state) do { \\");
  add "    state_var = (next_state); \\";
  add "} while(0); break";
  add "";
  add ("#define " ^ p ^ "CFF_EXIT(state_var) do { \\");
  add "    state_var = 0U; \\";
  add "} while(0); break";
  add "";
  add ("#define " ^ p ^ "CFF_END() \\");
  add "        default: \\";
  add "            state_var = 0U; \\";
  add "            break; \\";
  add "        } \\";
  add "    }";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 6. MARKER-BASED REGION PROTECTION (VMProtect Style SDK)                   */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add "  #if defined(__arm64__) || defined(__aarch64__)";
  add "    #define ASGARD_BEGIN_VIRTUALIZE(tag) \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_BEG_V____\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_MUTATION(tag) \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_BEG_M____\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_ULTRA(tag) \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_BEG_U____\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "    #define ASGARD_END() \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_END______\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "  #else";
  add "    #define ASGARD_BEGIN_VIRTUALIZE(tag) \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_BEG_V__\\\" \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_MUTATION(tag) \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_BEG_M__\\\" \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_ULTRA(tag) \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_BEG_U__\\\" \\n 1:\\n\\t\")";
  add "    #define ASGARD_END() \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_END____\\\" \\n 1:\\n\\t\")";
  add "  #endif";
  add "#else";
  add "  #define ASGARD_BEGIN_VIRTUALIZE(tag)";
  add "  #define ASGARD_BEGIN_MUTATION(tag)";
  add "  #define ASGARD_BEGIN_ULTRA(tag)";
  add "  #define ASGARD_END()";
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 7. COMPILE-TIME API HASHING & DYNAMIC RESOLUTION (IAT Elimination)        */";
  add "/* ------------------------------------------------------------------------- */";
  add ("static inline uint32_t " ^ p ^ "hash_api_str(const char* str) {");
  add "    uint32_t hash = 0x811C9DC5U;";
  add "    while (*str) {";
  add "        hash ^= (uint8_t)(*str++);";
  add "        hash *= 0x01000193U;";
  add "    }";
  add "    return hash;";
  add "}";
  add "";
  add "#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)";
  add "#include <dlfcn.h>";
  add ("static inline void* " ^ p ^ "resolve_api_by_hash(const char* const* known_symbols, size_t count, uint32_t target_hash) {");
  add "    for (size_t i = 0; i < count; ++i) {";
  add ("        if (" ^ p ^ "hash_api_str(known_symbols[i]) == target_hash) {");
  add "            return dlsym(RTLD_DEFAULT, known_symbols[i]);";
  add "        }";
  add "    }";
  add "    return (void*)0;";
  add "}";
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 8. HIGH-PRECISION ANTI-TRACE & HARDWARE TIMING WATCHDOG (RDTSC Guard)     */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__x86_64__) || defined(_M_X64)";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) {");
  add "    uint32_t lo, hi;";
  add "    __asm__ __volatile__(\"rdtsc\" : \"=a\"(lo), \"=d\"(hi));";
  add "    return (((uint64_t)hi) << 32) | (uint64_t)lo;";
  add "}";
  add "#elif defined(__aarch64__) || defined(__arm64__)";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) {");
  add "    uint64_t val;";
  add "    __asm__ __volatile__(\"mrs %0, cntvct_el0\" : \"=r\"(val));";
  add "    return val;";
  add "}";
  add "#else";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) { return 0ULL; }");
  add "#endif";
  add "";
  add ("#define " ^ p ^ "TIMING_GUARD_START(var_name) uint64_t var_name##_start = " ^ p ^ "read_cpu_ticks()");
  add ("#define " ^ p ^ "TIMING_GUARD_CHECK(var_name, max_ticks, on_tamper) do { \\");
  add ("    uint64_t var_name##_end = " ^ p ^ "read_cpu_ticks(); \\");
  add ("    if ((var_name##_end - var_name##_start) > (uint64_t)(max_ticks)) { \\");
  add "        on_tamper; \\";
  add "    } \\";
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 9. ACTIVE ANTI-DEBUGGING & HARDWARE BREAKPOINT PROBES (DR0..DR7 / sysctl) */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__APPLE__)";
  add "#include <sys/types.h>";
  add "#include <sys/sysctl.h>";
  add "#include <unistd.h>";
  add "#include <mach/mach.h>";
  add "#include <mach/thread_act.h>";
  add "";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) {");
  add "    int mib[4];";
  add "    struct kinfo_proc info;";
  add "    size_t size = sizeof(info);";
  add "    info.kp_proc.p_flag = 0;";
  add "    mib[0] = CTL_KERN;";
  add "    mib[1] = KERN_PROC;";
  add "    mib[2] = KERN_PROC_PID;";
  add "    mib[3] = getpid();";
  add "    if (sysctl(mib, 4, &info, &size, (void*)0, 0) == 0) {";
  add "        return (info.kp_proc.p_flag & P_TRACED) != 0;";
  add "    }";
  add "    return false;";
  add "}";
  add "";
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) {");
  add "#if defined(__x86_64__)";
  add "    x86_debug_state64_t dbg;";
  add "    mach_msg_type_number_t count = x86_DEBUG_STATE64_COUNT;";
  add "    if (thread_get_state(mach_thread_self(), x86_DEBUG_STATE64, (thread_state_t)&dbg, &count) == KERN_SUCCESS) {";
  add "        if (dbg.__dr0 || dbg.__dr1 || dbg.__dr2 || dbg.__dr3 || (dbg.__dr7 & 0xFF)) return true;";
  add "    }";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "    arm_debug_state64_t dbg;";
  add "    mach_msg_type_number_t count = ARM_DEBUG_STATE64_COUNT;";
  add "    if (thread_get_state(mach_thread_self(), ARM_DEBUG_STATE64, (thread_state_t)&dbg, &count) == KERN_SUCCESS) {";
  add "        for (int i = 0; i < 16; ++i) {";
  add "            if (dbg.__bvr[i] || (dbg.__bcr[i] & 1)) return true;";
  add "            if (dbg.__wvr[i] || (dbg.__wcr[i] & 1)) return true;";
  add "        }";
  add "    }";
  add "#endif";
  add "    return false;";
  add "}";
  add "#elif defined(__linux__)";
  add "#include <fcntl.h>";
  add "#include <unistd.h>";
  add "#include <string.h>";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) {");
  add "    int fd = open(\"/proc/self/status\", O_RDONLY);";
  add "    if (fd < 0) return false;";
  add "    char buf[512];";
  add "    ssize_t n = read(fd, buf, sizeof(buf) - 1);";
  add "    close(fd);";
  add "    if (n <= 0) return false;";
  add "    buf[n] = '\\0';";
  add "    const char* p_tracer = strstr(buf, \"TracerPid:\\t\");";
  add "    if (p_tracer) {";
  add "        p_tracer += 11;";
  add "        while (*p_tracer == ' ' || *p_tracer == '\\t') p_tracer++;";
  add "        if (*p_tracer > '0' && *p_tracer <= '9') return true;";
  add "    }";
  add "    return false;";
  add "}";
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) { return false; }");
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add "#include <windows.h>";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) { return IsDebuggerPresent(); }");
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) {");
  add "    CONTEXT ctx; memset(&ctx, 0, sizeof(ctx)); ctx.ContextFlags = CONTEXT_DEBUG_REGISTERS;";
  add "    if (GetThreadContext(GetCurrentThread(), &ctx)) {";
  add "        if (ctx.Dr0 || ctx.Dr1 || ctx.Dr2 || ctx.Dr3 || (ctx.Dr7 & 0xFF)) return true;";
  add "    }";
  add "    return false;";
  add "}";
  add "#else";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) { return false; }");
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) { return false; }");
  add "#endif";
  add "";
  add ("static inline bool " ^ p ^ "is_debugger_present(void) {");
  add ("    return " ^ p ^ "check_ptrace_sysctl() || " ^ p ^ "check_hw_breakpoints();");
  add "}";
  add "";
  add ("#define " ^ p ^ "ANTI_DEBUG_GUARD(on_debugger) do { \\");
  add ("    if (" ^ p ^ "is_debugger_present()) { \\");
  add "        on_debugger; \\";
  add "    } \\";
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 10. OPAQUE SIGNAL & EXCEPTION-BASED DISPATCHING (ucontext_t / SEH)        */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)";
  add "#include <signal.h>";
  add "#if defined(__APPLE__)";
  add "#include <sys/ucontext.h>";
  add "#else";
  add "#include <ucontext.h>";
  add "#endif";
  add "#include <string.h>";

  add "";
  add ("static volatile uintptr_t " ^ p ^ "sig_target = 0;");
  add "";
  add ("static void " ^ p ^ "signal_dispatcher_handler(int sig, siginfo_t* info, void* ucontext_ptr) {");
  add "    (void)sig;";
  add "    (void)info;";
  add ("    if (" ^ p ^ "sig_target != 0) {");
  add "        ucontext_t* uc = (ucontext_t*)ucontext_ptr;";
  add "#if defined(__APPLE__)";
  add "#if defined(__x86_64__)";
  add ("        uc->uc_mcontext->__ss.__rip = " ^ p ^ "sig_target;");
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add ("        uc->uc_mcontext->__ss.__pc = " ^ p ^ "sig_target;");
  add "#endif";
  add "#elif defined(__linux__)";
  add "#if defined(__x86_64__)";
  add ("        uc->uc_mcontext.gregs[REG_RIP] = (greg_t)" ^ p ^ "sig_target;");
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add ("        uc->uc_mcontext.pc = " ^ p ^ "sig_target;");
  add "#endif";
  add "#endif";
  add ("        " ^ p ^ "sig_target = 0;");
  add "    }";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_signal_dispatcher(void) {");
  add "    struct sigaction sa;";
  add "    memset(&sa, 0, sizeof(sa));";
  add ("    sa.sa_sigaction = " ^ p ^ "signal_dispatcher_handler;");
  add "    sa.sa_flags = SA_SIGINFO;";
  add "    sigemptyset(&sa.sa_mask);";
  add "    sigaction(SIGFPE, &sa, NULL);";
  add "    sigaction(SIGILL, &sa, NULL);";
  add "}";
  add "";
  add ("#define " ^ p ^ "SIG_DISPATCH_SETUP() " ^ p ^ "install_signal_dispatcher()");
  add ("#define " ^ p ^ "SIG_JUMP(target_ptr) do { \\");
  add ("    " ^ p ^ "sig_target = (uintptr_t)(target_ptr); \\");
  add "    raise(SIGILL); \\";
  add "} while(0)";
  add "";
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add "#include <windows.h>";
  add ("static volatile uintptr_t " ^ p ^ "sig_target = 0;");
  add "";
  add ("static LONG WINAPI " ^ p ^ "veh_handler(PEXCEPTION_POINTERS pExceptionInfo) {");
  add ("    if (" ^ p ^ "sig_target != 0) {");
  add "#if defined(_M_X64) || defined(__x86_64__)";
  add ("        pExceptionInfo->ContextRecord->Rip = (DWORD64)" ^ p ^ "sig_target;");
  add "#else";
  add ("        pExceptionInfo->ContextRecord->Eip = (DWORD)" ^ p ^ "sig_target;");
  add "#endif";
  add ("        " ^ p ^ "sig_target = 0;");
  add "        return EXCEPTION_CONTINUE_EXECUTION;";
  add "    }";
  add "    return EXCEPTION_CONTINUE_SEARCH;";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_signal_dispatcher(void) {");
  add ("    AddVectoredExceptionHandler(1, " ^ p ^ "veh_handler);");
  add "}";
  add "";
  add ("#define " ^ p ^ "SIG_DISPATCH_SETUP() " ^ p ^ "install_signal_dispatcher()");
  add ("#define " ^ p ^ "SIG_JUMP(target_ptr) do { \\");
  add ("    " ^ p ^ "sig_target = (uintptr_t)(target_ptr); \\");
  add "    RaiseException(0xE0000001, 0, 0, NULL); \\";
  add "} while(0)";
  add "#else";
  add ("#define " ^ p ^ "SIG_DISPATCH_SETUP() ((void)0)");
  add ("#define " ^ p ^ "SIG_JUMP(target_ptr) ((void)0)");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 11. MULTITHREADED NANOMITES & TRAP-AND-TRACE DISPATCHING                  */";
  add "/* ------------------------------------------------------------------------- */";
  add "typedef struct {";
  add "    uint32_t trap_id;";
  add "    uintptr_t target_true;";
  add "    uintptr_t target_false;";
  add "    uint32_t key;";
  add ("} " ^ p ^ "nanomite_entry_t;");
  add "";
  add ("static " ^ p ^ "nanomite_entry_t " ^ p ^ "nanomite_table[64];");
  add ("static size_t " ^ p ^ "nanomite_count = 0;");
  add ("static volatile uint32_t " ^ p ^ "current_trap_id = 0;");
  add ("static volatile uint32_t " ^ p ^ "current_condition = 0;");
  add "";
  add ("static inline void " ^ p ^ "register_nanomite(uint32_t trap_id, uintptr_t t_true, uintptr_t t_false, uint32_t key) {");
  add ("    if (" ^ p ^ "nanomite_count < 64) {");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].trap_id = trap_id;");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].target_true = t_true ^ (uintptr_t)key;");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].target_false = t_false ^ (uintptr_t)key;");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].key = key;");
  add ("        " ^ p ^ "nanomite_count++;");
  add "    }";
  add "}";
  add "";
  add "#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)";
  add ("static void " ^ p ^ "nanomite_trap_handler(int sig, siginfo_t* info, void* ucontext_ptr) {");
  add "    (void)sig; (void)info;";
  add "    ucontext_t* uc = (ucontext_t*)ucontext_ptr;";
  add ("    for (size_t i = 0; i < " ^ p ^ "nanomite_count; ++i) {");
  add ("        if (" ^ p ^ "nanomite_table[i].trap_id == " ^ p ^ "current_trap_id) {");
  add ("            uintptr_t enc_target = " ^ p ^ "current_condition ?");
  add ("                " ^ p ^ "nanomite_table[i].target_true :");
  add ("                " ^ p ^ "nanomite_table[i].target_false;");
  add ("            uintptr_t real_target = enc_target ^ (uintptr_t)" ^ p ^ "nanomite_table[i].key;");
  add "#if defined(__APPLE__)";
  add "#if defined(__x86_64__)";
  add "            uc->uc_mcontext->__ss.__rip = real_target;";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "            uc->uc_mcontext->__ss.__pc = real_target;";
  add "#endif";
  add "#elif defined(__linux__)";
  add "#if defined(__x86_64__)";
  add "            uc->uc_mcontext.gregs[REG_RIP] = (greg_t)real_target;";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "            uc->uc_mcontext.pc = real_target;";
  add "#endif";
  add "#endif";
  add ("            " ^ p ^ "current_trap_id = 0;");
  add "            return;";
  add "        }";
  add "    }";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_nanomites(void) {");
  add "    struct sigaction sa;";
  add "    memset(&sa, 0, sizeof(sa));";
  add ("    sa.sa_sigaction = " ^ p ^ "nanomite_trap_handler;");
  add "    sa.sa_flags = SA_SIGINFO;";
  add "    sigemptyset(&sa.sa_mask);";
  add "    sigaction(SIGTRAP, &sa, NULL);";
  add "}";

  add "";
  add ("#define " ^ p ^ "NANOMITE_INIT() " ^ p ^ "install_nanomites()");
  add ("#define " ^ p ^ "NANOMITE_REGISTER(id, t_true, t_false, key) " ^ p ^ "register_nanomite((id), (uintptr_t)(t_true), (uintptr_t)(t_false), (uint32_t)(key))");
  add ("#define " ^ p ^ "NANOMITE_DISPATCH(id, cond) do { \\");
  add ("    " ^ p ^ "current_trap_id = (id); \\");
  add ("    " ^ p ^ "current_condition = (cond) ? 1 : 0; \\");
  add "    raise(SIGTRAP); \\";
  add "} while(0)";
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add ("static LONG WINAPI " ^ p ^ "nanomite_veh_handler(PEXCEPTION_POINTERS pExceptionInfo) {");
  add ("    if (pExceptionInfo->ExceptionRecord->ExceptionCode == EXCEPTION_BREAKPOINT || pExceptionInfo->ExceptionRecord->ExceptionCode == 0xE0000002) {");
  add ("        for (size_t i = 0; i < " ^ p ^ "nanomite_count; ++i) {");
  add ("            if (" ^ p ^ "nanomite_table[i].trap_id == " ^ p ^ "current_trap_id) {");
  add ("                uintptr_t enc_target = " ^ p ^ "current_condition ?");
  add ("                    " ^ p ^ "nanomite_table[i].target_true :");
  add ("                    " ^ p ^ "nanomite_table[i].target_false;");
  add ("                uintptr_t real_target = enc_target ^ (uintptr_t)" ^ p ^ "nanomite_table[i].key;");
  add "#if defined(_M_X64) || defined(__x86_64__)";
  add "                pExceptionInfo->ContextRecord->Rip = (DWORD64)real_target;";
  add "#else";
  add "                pExceptionInfo->ContextRecord->Eip = (DWORD)real_target;";
  add "#endif";
  add ("                " ^ p ^ "current_trap_id = 0;");
  add "                return EXCEPTION_CONTINUE_EXECUTION;";
  add "            }";
  add "        }";
  add "    }";
  add "    return EXCEPTION_CONTINUE_SEARCH;";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_nanomites(void) {");
  add ("    AddVectoredExceptionHandler(1, " ^ p ^ "nanomite_veh_handler);");
  add "}";
  add "";
  add ("#define " ^ p ^ "NANOMITE_INIT() " ^ p ^ "install_nanomites()");
  add ("#define " ^ p ^ "NANOMITE_REGISTER(id, t_true, t_false, key) " ^ p ^ "register_nanomite((id), (uintptr_t)(t_true), (uintptr_t)(t_false), (uint32_t)(key))");
  add ("#define " ^ p ^ "NANOMITE_DISPATCH(id, cond) do { \\");
  add ("    " ^ p ^ "current_trap_id = (id); \\");
  add ("    " ^ p ^ "current_condition = (cond) ? 1 : 0; \\");
  add "    RaiseException(0xE0000002, 0, 0, NULL); \\";
  add "} while(0)";
  add "#else";
  add ("#define " ^ p ^ "NANOMITE_INIT() ((void)0)");
  add ("#define " ^ p ^ "NANOMITE_REGISTER(id, t_true, t_false, key) ((void)0)");
  add ("#define " ^ p ^ "NANOMITE_DISPATCH(id, cond) ((void)0)");
  add "#endif";
  add "";
  add "#endif /* _ASGARD_OBF_H_ */";




  Buffer.contents b


(* =========================================================================== *)
(* Nanomite Auto-Lifter: if (cond) { ... } else { ... } → ASG_NANOMITE_DISPATCH *)
(* =========================================================================== *)

(** Skip whitespace forward from position [i] in [s], return new index. *)
let skip_ws s i =
  let len = String.length s in
  let j = ref i in
  while !j < len && (s.[!j] = ' ' || s.[!j] = '\t' || s.[!j] = '\n' || s.[!j] = '\r') do
    incr j
  done;
  !j

(** Scan balanced braces starting at [i] (which must be '{').
    Returns the index just AFTER the matching '}'. *)
let scan_balanced_braces s i =
  let len = String.length s in
  let depth = ref 0 in
  let j = ref i in
  let in_str = ref false in
  let in_char = ref false in
  let escape = ref false in
  while !j < len && (not (!depth = 0 && !j > i)) do
    let c = s.[!j] in
    (if !escape then escape := false
     else match c with
       | '\\' when !in_str || !in_char -> escape := true
       | '"' when not !in_char -> in_str := not !in_str
       | '\'' when not !in_str -> in_char := not !in_char
       | '{' when not !in_str && not !in_char -> incr depth
       | '}' when not !in_str && not !in_char -> decr depth
       | _ -> ());
    incr j
  done;
  if !depth = 0 then !j else -1

(** Scan balanced parentheses starting at [i] (which must be '(').
    Returns the index just AFTER the matching ')'. *)
let scan_balanced_parens s i =
  let len = String.length s in
  let depth = ref 0 in
  let j = ref i in
  let in_str = ref false in
  let escape = ref false in
  while !j < len && (not (!depth = 0 && !j > i)) do
    let c = s.[!j] in
    (if !escape then escape := false
     else match c with
       | '\\' when !in_str -> escape := true
       | '"' -> in_str := not !in_str
       | '(' when not !in_str -> incr depth
       | ')' when not !in_str -> decr depth
       | _ -> ());
    incr j
  done;
  if !depth = 0 then !j else -1

(** One parsed nanomite site. *)
type nanomite_site = {
  ns_id       : int;
  ns_cond     : string;
  ns_then_fn  : string;
  ns_else_fn  : string;
  ns_then_src : string;
  ns_else_src : string;
  ns_key      : int;
}

(** Try to parse one [if (cond) { then } [else { else }]] starting at [pos].
    Returns (site, end_pos) or None. *)
let try_parse_if src pos rng_state seed_ref prefix =
  let len = String.length src in
  if pos + 2 > len then None
  else if not (String.sub src pos 2 = "if") then None
  else
    let before_ok =
      pos = 0 ||
      (let c = src.[pos-1] in
       not (c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c = '_'))
    in
    if not before_ok then None
    else
      let after = skip_ws src (pos + 2) in
      if after >= len || src.[after] <> '(' then None
      else
        let cond_end = scan_balanced_parens src after in
        if cond_end < 0 then None
        else
          let cond_text = String.sub src (after + 1) (cond_end - after - 2) in
          let body_start = skip_ws src cond_end in
          if body_start >= len || src.[body_start] <> '{' then None
          else
            let then_end = scan_balanced_braces src body_start in
            if then_end < 0 then None
            else
              let then_body = String.sub src (body_start + 1) (then_end - body_start - 2) in
              let after_then = skip_ws src then_end in
              let else_body, total_end =
                if after_then + 4 <= len && String.sub src after_then 4 = "else" &&
                   (after_then + 4 >= len ||
                    (let c = src.[after_then + 4] in
                     c = ' ' || c = '\t' || c = '\n' || c = '\r' || c = '{'))
                then
                  let else_brace = skip_ws src (after_then + 4) in
                  if else_brace >= len || src.[else_brace] <> '{' then ("", then_end)
                  else
                    let else_end = scan_balanced_braces src else_brace in
                    if else_end < 0 then ("", then_end)
                    else
                      let eb = String.sub src (else_brace + 1) (else_end - else_brace - 2) in
                      (eb, else_end)
                else ("", then_end)
              in
              let id = (xorshift32 !seed_ref) land 0xFFFF in
              seed_ref := xorshift32 !seed_ref;
              let key = Int64.to_int (Int64.logand (rand_u64 rng_state) 0x7FFFFFFFL) in
              let idx = !seed_ref land 0x7FFFF in
              let then_fn = Printf.sprintf "%sasgbranch_t_%d" prefix idx in
              let else_fn = Printf.sprintf "%sasgbranch_f_%d" prefix idx in
              Some ({
                ns_id       = id;
                ns_cond     = cond_text;
                ns_then_fn  = then_fn;
                ns_else_fn  = else_fn;
                ns_then_src = then_body;
                ns_else_src = else_body;
                ns_key      = key;
              }, total_end)

(** Lift all if-statements in [src] to nanomites.
    Returns (transformed_src, list_of_sites). *)
let lift_ifs_to_nanomites ?(config = default_config) src =
  let p = config.macro_prefix in
  let rng = Random.State.make [| config.seed lxor 0xDEADC0DE |] in
  let seed_ref = ref (config.seed lxor 0x5A5A5A5A) in
  let len = String.length src in
  let buf = Buffer.create (len * 2) in
  let sites = ref [] in
  let in_marker = ref false in
  let i = ref 0 in
  while !i < len do
    let c = src.[!i] in
    (* Marker detection: preserve VM virtualization regions *)
    if !i + 12 <= len && String.sub src !i 12 = "ASGARD_BEGIN" then begin
      in_marker := true;
      Buffer.add_char buf c;
      incr i
    end
    else if !i + 10 <= len && String.sub src !i 10 = "ASGARD_END" then begin
      in_marker := false;
      Buffer.add_char buf c;
      incr i
    end
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '/' then begin
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i]; incr i
      done
    end
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '*' then begin
      Buffer.add_char buf src.[!i];
      Buffer.add_char buf src.[!i + 1];
      i := !i + 2;
      while !i + 1 < len && not (src.[!i] = '*' && src.[!i + 1] = '/') do
        Buffer.add_char buf src.[!i]; incr i
      done;
      if !i + 1 < len then begin
        Buffer.add_char buf src.[!i];
        Buffer.add_char buf src.[!i + 1];
        i := !i + 2
      end
    end
    else if c = '"' then begin
      Buffer.add_char buf c; incr i;
      let escaped = ref false in
      let closed = ref false in
      while !i < len && not !closed do
        let sc = src.[!i] in
        Buffer.add_char buf sc;
        if !escaped then begin
          escaped := false;
          incr i
        end
        else if sc = '\\' then begin
          escaped := true;
          incr i
        end
        else if sc = '"' then begin
          closed := true;
          incr i
        end
        else begin
          incr i
        end
      done
    end
    else if c = '#' then begin
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i]; incr i
      done
    end
    else if (not !in_marker) && c = 'i' && !i + 1 < len && src.[!i + 1] = 'f' then begin
      match try_parse_if src !i rng seed_ref p with
      | None ->
        Buffer.add_char buf c; incr i
      | Some (site, end_pos) ->
        Buffer.add_string buf
          (Printf.sprintf "ASG_NANOMITE_DISPATCH(%d, (%s));" site.ns_id site.ns_cond);
        sites := site :: !sites;
        i := end_pos
    end
    else begin
      Buffer.add_char buf c; incr i
    end
  done;
  (Buffer.contents buf, List.rev !sites)

(** Strip [return expr;] and bare [return;] from a C body string.
    Branch functions are [void], so we replace:
    - [return <expr>;] → [(void)(<expr>);]
    - [return;]        → [(void)0;] *)
let strip_returns_from_body body =
  let len = String.length body in
  let buf = Buffer.create (len + 16) in
  let i = ref 0 in
  while !i < len do
    (* Look for "return" keyword *)
    if !i + 6 <= len && String.sub body !i 6 = "return" &&
       (!i = 0 ||
        (let c = body.[!i - 1] in
         not (c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c = '_')))
    then begin
      let after = ref (!i + 6) in
      (* skip optional whitespace *)
      while !after < len && (body.[!after] = ' ' || body.[!after] = '\t') do incr after done;
      if !after < len && body.[!after] = ';' then begin
        (* bare return; → (void)0; *)
        Buffer.add_string buf "(void)0;";
        i := !after + 1
      end else begin
        (* return <expr>; — find the matching semicolon at depth 0 *)
        let depth = ref 0 in
        let expr_start = !after in
        let sc_pos = ref (-1) in
        let j = ref expr_start in
        while !j < len && !sc_pos = -1 do
          let c = body.[!j] in
          (match c with
           | '(' | '[' | '{' -> incr depth
           | ')' | ']' | '}' -> decr depth
           | ';' when !depth = 0 -> sc_pos := !j
           | _ -> ());
          incr j
        done;
        if !sc_pos >= 0 then begin
          let expr = String.sub body expr_start (!sc_pos - expr_start) in
          let trimmed = String.trim expr in
          if trimmed = "" then
            Buffer.add_string buf "(void)0;"
          else
            Buffer.add_string buf (Printf.sprintf "(void)(%s);" trimmed);
          i := !sc_pos + 1
        end else begin
          (* malformed: copy verbatim *)
          Buffer.add_string buf "return";
          i := !i + 6
        end
      end
    end
    else begin
      Buffer.add_char buf body.[!i];
      incr i
    end
  done;
  Buffer.contents buf

(** Extract a leading block of preprocessor directives (#include, #define, etc.)
    from the beginning of a source string.
    Returns (directives_block, rest_of_source). *)
let split_leading_directives src =
  let len = String.length src in
  let i = ref 0 in
  let end_of_directives = ref 0 in
  (* Walk through any leading lines that are blank or start with '#' *)
  let continue_scan = ref true in
  while !continue_scan && !i < len do
    (* skip whitespace/blank lines *)
    while !i < len && (src.[!i] = ' ' || src.[!i] = '\t' || src.[!i] = '\n' || src.[!i] = '\r') do
      incr i
    done;
    if !i < len && src.[!i] = '#' then begin
      (* consume until end of line *)
      while !i < len && src.[!i] <> '\n' do incr i done;
      if !i < len then incr i;  (* consume the newline *)
      end_of_directives := !i
    end else
      continue_scan := false
  done;
  let directives = String.sub src 0 !end_of_directives in
  let rest = String.sub src !end_of_directives (len - !end_of_directives) in
  (directives, rest)

(** Given nanomite sites, emit branch functions + __attribute__((constructor))
    auto-registration block. *)
let emit_nanomite_preamble ?(config = default_config) sites =
  let p = config.macro_prefix in
  let buf = Buffer.create 1024 in
  List.iter (fun s ->
    let then_body = strip_returns_from_body s.ns_then_src in
    Buffer.add_string buf
      (Printf.sprintf "static void __attribute__((noinline)) %s(void) {\n%s\n}\n"
         s.ns_then_fn then_body);
    let else_raw = if String.trim s.ns_else_src = "" then "    (void)0;" else s.ns_else_src in
    let else_body = strip_returns_from_body else_raw in
    Buffer.add_string buf
      (Printf.sprintf "static void __attribute__((noinline)) %s(void) {\n%s\n}\n"
         s.ns_else_fn else_body);
  ) sites;
  Buffer.add_char buf '\n';
  Buffer.add_string buf "__attribute__((constructor)) static void _asg_nanomite_auto_init_(void) {\n";
  Buffer.add_string buf (Printf.sprintf "    %sNANOMITE_INIT();\n" p);
  List.iter (fun s ->
    Buffer.add_string buf
      (Printf.sprintf "    %sNANOMITE_REGISTER(%d, %s, %s, 0x%Xu);\n"
         p s.ns_id s.ns_then_fn s.ns_else_fn s.ns_key)
  ) sites;
  Buffer.add_string buf "}\n\n";
  Buffer.contents buf

(** Fully lift a C source string: if/else blocks → nanomites.
    Returns (transformed_body, preamble_to_prepend).
    The preamble already includes the leading #include/#define block from the
    original source so that branch functions compile without missing declarations. *)
let lift_nanomites_in_source ?(config = default_config) src =
  (* Split off leading preprocessor directives so branch functions can see them *)
  let (leading_directives, body) = split_leading_directives src in
  let (transformed_body, sites) = lift_ifs_to_nanomites ~config body in
  if sites = [] then
    (* No if found: return full source unchanged, no preamble *)
    (src, "")
  else begin
    let fn_preamble = emit_nanomite_preamble ~config sites in
    (* Preamble = leading directives + branch functions + constructor *)
    let preamble = leading_directives ^ "\n" ^ fn_preamble in
    (* transformed is the directives-stripped body with if→dispatch *)
    (transformed_body, preamble)
  end

(** Obfuscate a raw string into an inline stack-decrypted C macro expression *)
let obfuscate_string_literal ~prefix ~seed s =
  let len = String.length s in
  let key = (xorshift32 (seed + len * 31)) land 0x7FFFFFFF in
  let bytes = Buffer.create (len * 6 + 10) in
  Buffer.add_string bytes "{ ";
  for i = 0 to len - 1 do
    let orig_byte = Char.code s.[i] in
    let k = ((key lxor (i * 0x5D)) land 0xFF) in
    let enc_byte = orig_byte lxor k in
    if i > 0 then Buffer.add_string bytes ", ";
    Buffer.add_string bytes (Printf.sprintf "0x%02X" enc_byte)
  done;
  if len = 0 then Buffer.add_string bytes "0x00";
  Buffer.add_string bytes " }";
  Printf.sprintf "%sSTR(((const uint8_t[])%s), %d, 0x%XU)" prefix (Buffer.contents bytes) len key

(** Obfuscate an integer constant *)
let obfuscate_constant_i64 ~prefix ~seed n =
  let rng = Random.State.make [| seed; Int64.to_int (Int64.logand n 0x7FFFFFFFL) |] in
  let k1 = rand_u64 rng in
  let k2 = rand_u64 rng in
  let c1 = Int64.logxor n k1 in
  Printf.sprintf "%sBLIND_I64(0x%LXULL, 0x%LXULL, 0x%LXULL)" prefix c1 k1 k2

(* ======================================================================== *)
(*  Phase 3: C Arithmetic Expression AST Rewriter                           *)
(*                                                                           *)
(*  Lexes C tokens, parses expressions with correct operator precedence,    *)
(*  builds an AST, and reprints with MBA macro wrappers for:                *)
(*    +  → ASG_MBA_ADD    -  → ASG_MBA_SUB    ^  → ASG_MBA_XOR             *)
(*    &  → ASG_MBA_AND    |  → ASG_MBA_OR     ~  → ASG_MBA_NOT             *)
(*                                                                           *)
(*  The rewriter is statement-aware: it only rewrites expressions inside    *)
(*  assignment RHS, return expressions, and initializer expressions.        *)
(*  It does NOT touch:                                                       *)
(*    • Preprocessor directives (#include, #define …)                       *)
(*    • String literals                                                      *)
(*    • Comments                                                             *)
(*    • Pointer arithmetic (e.g. p + 1) — conservatively left alone        *)
(*    • Function-like macro calls already starting with the macro prefix    *)
(* ======================================================================== *)

(* ─── Lexer tokens ──────────────────────────────────────────────────────── *)
type c_tok =
  | TPlus | TMinus | TStar | TSlash | TPercent
  | TAmpersand | TPipe | TCaret | TTilde | TBang
  | TLShift | TRShift
  | TLParen | TRParen | TLBracket | TRBracket | TLBrace | TRBrace
  | TComma | TSemicolon | TColon | TQuestion
  | TEq | TAddEq | TSubEq | TAndEq | TOrEq | TXorEq | TMulEq | TDivEq
  | TArrow | TDot
  | TEqEq | TNotEq | TLe | TGe | TLt | TGt
  | TAnd | TOr  (* && || *)
  | TIdent of string
  | TIntLit of string   (* keep verbatim so we never lose suffixes, covers floats too *)
  | TCharLit of string
  | TStrLit of string   (* content including quotes *)
  | TIncDec of string   (* ++ or -- *)
  | TEOF

let c_lex src =
  (* Returns array of (token, start_pos, end_pos) for whole src *)
  let len = String.length src in
  let toks = Buffer.create 256 in
  let result = ref [] in
  let push tok s e = result := (tok, s, e) :: !result in
  let i = ref 0 in
  let read_while pred =
    let start = !i in
    while !i < len && pred src.[!i] do incr i done;
    String.sub src start (!i - start)
  in
  let is_ident_start c = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c = '_' in
  let is_ident c = is_ident_start c || (c >= '0' && c <= '9') in
  let is_digit c = c >= '0' && c <= '9' in
  let is_hex c = is_digit c || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F') in
  ignore toks;
  while !i < len do
    let start = !i in
    let c = src.[!i] in
    (* Skip whitespace, copy it as TIdent-like — actually we handle whitespace differently:
       we'll just read the token and record positions *)
    if c = ' ' || c = '\t' || c = '\n' || c = '\r' then incr i
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '/' then begin
      (* line comment *)
      while !i < len && src.[!i] <> '\n' do incr i done;
      push (TStrLit (String.sub src start (!i - start))) start !i
    end
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '*' then begin
      i := !i + 2;
      while !i + 1 < len && not (src.[!i] = '*' && src.[!i+1] = '/') do incr i done;
      if !i + 1 < len then i := !i + 2;
      push (TStrLit (String.sub src start (!i - start))) start !i
    end
    else if c = '"' then begin
      incr i;
      let escaped = ref false in
      while !i < len && (src.[!i] <> '"' || !escaped) do
        if !escaped then escaped := false
        else if src.[!i] = '\\' then escaped := true;
        incr i
      done;
      if !i < len then incr i;
      push (TStrLit (String.sub src start (!i - start))) start !i
    end
    else if c = '\'' then begin
      incr i;
      let escaped = ref false in
      while !i < len && (src.[!i] <> '\'' || !escaped) do
        if !escaped then escaped := false
        else if src.[!i] = '\\' then escaped := true;
        incr i
      done;
      if !i < len then incr i;
      push (TCharLit (String.sub src start (!i - start))) start !i
    end
    else if c = '#' then begin
      (* preprocessor line: consume to end of logical line *)
      while !i < len && src.[!i] <> '\n' do incr i done;
      push (TStrLit (String.sub src start (!i - start))) start !i
    end
    else if is_ident_start c then begin
      let name = read_while is_ident in
      push (TIdent name) start !i
    end
    else if is_digit c || (c = '.' && !i + 1 < len && is_digit src.[!i+1]) then begin
      (* integer or float literal with optional suffixes *)
      let is_0x = c = '0' && !i + 1 < len && (src.[!i+1] = 'x' || src.[!i+1] = 'X') in
      if is_0x then begin
        i := !i + 2;
        let _ = read_while is_hex in ()
      end else begin
        let _ = read_while is_digit in
        if !i < len && src.[!i] = '.' then begin
          incr i;
          let _ = read_while is_digit in ()
        end;
        if !i < len && (src.[!i] = 'e' || src.[!i] = 'E') then begin
          incr i;
          if !i < len && (src.[!i] = '+' || src.[!i] = '-') then incr i;
          let _ = read_while is_digit in ()
        end
      end;
      (* consume suffixes u U l L f F *)
      while !i < len && (let ch = src.[!i] in
        ch='u'||ch='U'||ch='l'||ch='L'||ch='f'||ch='F') do incr i done;
      let lit = String.sub src start (!i - start) in
      push (TIntLit lit) start !i
    end
    else begin
      (* operators and punctuation *)
      let tok, advance =
        match c with
        | '+' when !i+1 < len && src.[!i+1] = '+' -> TIncDec "++", 2
        | '+' when !i+1 < len && src.[!i+1] = '=' -> TAddEq, 2
        | '+' -> TPlus, 1
        | '-' when !i+1 < len && src.[!i+1] = '-' -> TIncDec "--", 2
        | '-' when !i+1 < len && src.[!i+1] = '=' -> TSubEq, 2
        | '-' when !i+1 < len && src.[!i+1] = '>' -> TArrow, 2
        | '-' -> TMinus, 1
        | '*' when !i+1 < len && src.[!i+1] = '=' -> TMulEq, 2
        | '*' -> TStar, 1
        | '/' when !i+1 < len && src.[!i+1] = '=' -> TDivEq, 2
        | '/' -> TSlash, 1
        | '%' -> TPercent, 1
        | '&' when !i+1 < len && src.[!i+1] = '&' -> TAnd, 2
        | '&' when !i+1 < len && src.[!i+1] = '=' -> TAndEq, 2
        | '&' -> TAmpersand, 1
        | '|' when !i+1 < len && src.[!i+1] = '|' -> TOr, 2
        | '|' when !i+1 < len && src.[!i+1] = '=' -> TOrEq, 2
        | '|' -> TPipe, 1
        | '^' when !i+1 < len && src.[!i+1] = '=' -> TXorEq, 2
        | '^' -> TCaret, 1
        | '~' -> TTilde, 1
        | '!' when !i+1 < len && src.[!i+1] = '=' -> TNotEq, 2
        | '!' -> TBang, 1
        | '<' when !i+1 < len && src.[!i+1] = '<' -> TLShift, 2
        | '<' when !i+1 < len && src.[!i+1] = '=' -> TLe, 2
        | '<' -> TLt, 1
        | '>' when !i+1 < len && src.[!i+1] = '>' -> TRShift, 2
        | '>' when !i+1 < len && src.[!i+1] = '=' -> TGe, 2
        | '>' -> TGt, 1
        | '=' when !i+1 < len && src.[!i+1] = '=' -> TEqEq, 2
        | '=' -> TEq, 1
        | '(' -> TLParen, 1
        | ')' -> TRParen, 1
        | '[' -> TLBracket, 1
        | ']' -> TRBracket, 1
        | '{' -> TLBrace, 1
        | '}' -> TRBrace, 1
        | ',' -> TComma, 1
        | ';' -> TSemicolon, 1
        | ':' -> TColon, 1
        | '?' -> TQuestion, 1
        | '.' -> TDot, 1
        | _ -> TIdent (String.make 1 c), 1
      in
      i := !i + advance;
      push tok start !i
    end
  done;
  push TEOF !i !i;
  Array.of_list (List.rev !result)

(* ─── Simple C-expression AST (only for rewriting arithmetic) ──────────── *)
type c_expr =
  | ELit   of string           (* verbatim token *)
  | EIdent of string
  | EParen of c_expr
  | ECall  of c_expr * c_expr list
  | EIndex of c_expr * c_expr
  | EField of c_expr * string * bool   (* e.field or e->field (bool=arrow) *)
  | EPostfix of c_expr * string        (* ++ -- *)
  | EPrefix of string * c_expr         (* ++ -- & * ~ ! - + *)
  | ECast  of string * c_expr          (* (type) expr *)
  | EBinop of string * c_expr * c_expr
  | ETernary of c_expr * c_expr * c_expr

(* ─── Printer with MBA macro substitution ────────────────────────────────── *)
let rec print_expr ~prefix ~depth ~mba expr =
  let sub = print_expr ~prefix ~depth:(depth - 1) ~mba in
  match expr with
  | ELit s | EIdent s -> s
  | EParen e -> "(" ^ sub e ^ ")"
  | ECall (f, args) ->
      sub f ^ "(" ^ String.concat ", " (List.map sub args) ^ ")"
  | EIndex (e, idx) -> sub e ^ "[" ^ sub idx ^ "]"
  | EField (e, name, arrow) ->
      sub e ^ (if arrow then "->" else ".") ^ name
  | EPostfix (e, op) -> sub e ^ op
  | EPrefix (op, e) -> op ^ sub e
  | ECast (ty, e) -> "(" ^ ty ^ ")" ^ sub e
  | ETernary (cond, t, f) ->
      sub cond ^ " ? " ^ sub t ^ " : " ^ sub f
  | EBinop (op, a, b) ->
      if mba && depth > 0 then begin
        let sa = sub a and sb = sub b in
        match op with
        | "+"  -> Printf.sprintf "%sMBA_ADD(%s, %s)" prefix sa sb
        | "-"  -> Printf.sprintf "%sMBA_SUB(%s, %s)" prefix sa sb
        | "^"  -> Printf.sprintf "%sMBA_XOR(%s, %s)" prefix sa sb
        | "&"  -> Printf.sprintf "%sMBA_AND(%s, %s)" prefix sa sb
        | "|"  -> Printf.sprintf "%sMBA_OR(%s, %s)"  prefix sa sb
        | _    -> sa ^ " " ^ op ^ " " ^ sb
      end else
        sub a ^ " " ^ op ^ " " ^ sub b

(* ─── Recursive-descent parser ──────────────────────────────────────────── *)

(* Returns (expr, next_token_index) *)
let parse_expr toks start_idx =
  let n = Array.length toks in
  let pos = ref start_idx in
  let peek () = if !pos < n then let (t,_,_) = toks.(!pos) in t else TEOF in
  let advance () = incr pos in
  let consume () =
    let (t,s,e) = toks.(!pos) in
    incr pos; (t,s,e)
  in

  (* collect verbatim text between two positions in toks *)
  let src_between a b =
    (* a and b are token indices; we reconstruct from end of tok a-1 to start of tok b *)
    if a >= b then ""
    else begin
      let (_,_,ea) = toks.(a - 1) in
      let (_,sb,_) = toks.(b) in
      ignore ea; ignore sb; ""  (* placeholder — we use the AST path *)
    end
  in
  ignore src_between;

  let tok_str tok =
    match tok with
    | TIdent s | TIntLit s | TCharLit s | TStrLit s -> s
    | TPlus -> "+" | TMinus -> "-" | TStar -> "*" | TSlash -> "/" | TPercent -> "%"
    | TAmpersand -> "&" | TPipe -> "|" | TCaret -> "^" | TTilde -> "~" | TBang -> "!"
    | TLShift -> "<<" | TRShift -> ">>" | TLt -> "<" | TGt -> ">" | TLe -> "<=" | TGe -> ">="
    | TEqEq -> "==" | TNotEq -> "!=" | TAnd -> "&&" | TOr -> "||"
    | TIncDec s -> s
    | TArrow -> "->" | TDot -> "."
    | TEq -> "=" | TAddEq -> "+=" | TSubEq -> "-=" | TAndEq -> "&=" | TOrEq -> "|=" | TXorEq -> "^=" | TMulEq -> "*=" | TDivEq -> "/="
    | TLParen -> "(" | TRParen -> ")" | TLBracket -> "[" | TRBracket -> "]" | TLBrace -> "{" | TRBrace -> "}"
    | TComma -> "," | TSemicolon -> ";" | TColon -> ":" | TQuestion -> "?"
    | TEOF -> ""
  in

  (* Check if an ident is a type keyword (for cast detection) *)
  let is_type_kw = function
    | "int" | "char" | "short" | "long" | "unsigned" | "signed"
    | "float" | "double" | "void" | "bool" | "size_t" | "ssize_t"
    | "uint8_t" | "uint16_t" | "uint32_t" | "uint64_t"
    | "int8_t"  | "int16_t"  | "int32_t"  | "int64_t"
    | "intptr_t" | "uintptr_t" | "ptrdiff_t"
    | "const" | "volatile" | "struct" | "union" | "enum" -> true
    | _ -> false
  in

  (* --- primary --- *)
  let rec parse_primary () =
    match peek () with
    | TLParen ->
        advance ();
        (* Could be cast: (type) expr or parenthesised expr *)
        let saved = !pos in
        (* Try to detect cast: peek at what's inside *)
        let is_cast =
          (match peek () with
          | TIdent name when is_type_kw name ->
              (* scan forward past type tokens including * const etc *)
              let j = ref !pos in
              while !j < n && (match (let (t,_,_)=toks.(!j) in t) with
                | TIdent s when is_type_kw s || s = "const" || s = "volatile" -> true
                | TStar -> true
                | _ -> false) do incr j done;
              (match (let (t,_,_)=toks.(!j) in t) with TRParen -> true | _ -> false)
          | _ -> false)
        in
        if is_cast then begin
          let type_toks = Buffer.create 16 in
          let first = ref true in
          while (match peek () with TRParen | TEOF -> false | _ -> true) do
            if not !first then Buffer.add_char type_toks ' ';
            first := false;
            let (t,_,_) = consume () in
            Buffer.add_string type_toks (tok_str t)
          done;
          let ty = Buffer.contents type_toks in
          advance ();  (* consume ) *)
          let e = parse_unary () in
          ECast (ty, e)
        end else begin
          pos := saved;
          let e = parse_ternary () in
          (match peek () with TRParen -> advance () | _ -> ());
          EParen e
        end
    | TIdent name ->
        advance ();
        EIdent name
    | TIntLit s ->
        advance (); ELit s
    | TCharLit s ->
        advance (); ELit s
    | TStrLit s ->
        (* string literal — may be adjacent: "a" "b" *)
        let buf = Buffer.create (String.length s) in
        Buffer.add_string buf s;
        advance ();
        while (match peek () with TStrLit _ -> true | _ -> false) do
          let (t,_,_) = consume () in
          Buffer.add_char buf ' ';
          Buffer.add_string buf (tok_str t)
        done;
        ELit (Buffer.contents buf)
    | _ ->
        let (t,_,_) = consume () in
        ELit (tok_str t)

  and parse_postfix () =
    let e = ref (parse_primary ()) in
    let continue_loop = ref true in
    while !continue_loop do
      (match peek () with
      | TLParen ->
          (* function call *)
          advance ();
          let args = ref [] in
          if peek () <> TRParen then begin
            args := [parse_assignment ()];
            while peek () = TComma do
              advance ();
              args := !args @ [parse_assignment ()]
            done
          end;
          (match peek () with TRParen -> advance () | _ -> ());
          e := ECall (!e, !args)
      | TLBracket ->
          advance ();
          let idx = parse_ternary () in
          (match peek () with TRBracket -> advance () | _ -> ());
          e := EIndex (!e, idx)
      | TDot ->
          advance ();
          let name = (match peek () with
            | TIdent s -> advance (); s
            | _ -> "") in
          e := EField (!e, name, false)
      | TArrow ->
          advance ();
          let name = (match peek () with
            | TIdent s -> advance (); s
            | _ -> "") in
          e := EField (!e, name, true)
      | TIncDec s ->
          advance ();
          e := EPostfix (!e, s)
      | _ -> continue_loop := false)
    done;
    !e

  and parse_unary () =
    match peek () with
    | TMinus ->
        advance (); let e = parse_unary () in EPrefix ("-", e)
    | TPlus ->
        advance (); let e = parse_unary () in EPrefix ("+", e)
    | TTilde ->
        advance (); let e = parse_unary () in EPrefix ("~", e)
    | TBang ->
        advance (); let e = parse_unary () in EPrefix ("!", e)
    | TAmpersand ->
        (* address-of — do NOT obfuscate, treat as raw *)
        advance (); let e = parse_unary () in EPrefix ("&", e)
    | TStar ->
        (* dereference *)
        advance (); let e = parse_unary () in EPrefix ("*", e)
    | TIncDec s ->
        advance (); let e = parse_unary () in EPrefix (s, e)
    | _ -> parse_postfix ()

  and parse_mul () =
    let e = ref (parse_unary ()) in
    let continue_loop = ref true in
    while !continue_loop do
      (match peek () with
      | TStar ->
          advance ();
          let r = parse_unary () in
          e := EBinop ("*", !e, r)
      | TSlash ->
          advance ();
          let r = parse_unary () in
          e := EBinop ("/", !e, r)
      | TPercent ->
          advance ();
          let r = parse_unary () in
          e := EBinop ("%", !e, r)
      | _ -> continue_loop := false)
    done;
    !e

  and parse_add () =
    let e = ref (parse_mul ()) in
    let continue_loop = ref true in
    while !continue_loop do
      (match peek () with
      | TPlus ->
          advance ();
          let r = parse_mul () in
          e := EBinop ("+", !e, r)
      | TMinus ->
          advance ();
          let r = parse_mul () in
          e := EBinop ("-", !e, r)
      | _ -> continue_loop := false)
    done;
    !e

  and parse_shift () =
    let e = ref (parse_add ()) in
    let continue_loop = ref true in
    while !continue_loop do
      (match peek () with
      | TLShift ->
          advance (); let r = parse_add () in
          e := EBinop ("<<", !e, r)
      | TRShift ->
          advance (); let r = parse_add () in
          e := EBinop (">>", !e, r)
      | _ -> continue_loop := false)
    done;
    !e

  and parse_rel () =
    let e = ref (parse_shift ()) in
    let continue_loop = ref true in
    while !continue_loop do
      (match peek () with
      | TLt  -> advance (); let r = parse_shift () in e := EBinop ("<",  !e, r)
      | TGt  -> advance (); let r = parse_shift () in e := EBinop (">",  !e, r)
      | TLe  -> advance (); let r = parse_shift () in e := EBinop ("<=", !e, r)
      | TGe  -> advance (); let r = parse_shift () in e := EBinop (">=", !e, r)
      | TEqEq -> advance (); let r = parse_shift () in e := EBinop ("==", !e, r)
      | TNotEq -> advance (); let r = parse_shift () in e := EBinop ("!=", !e, r)
      | _ -> continue_loop := false)
    done;
    !e

  and parse_bitand () =
    let e = ref (parse_rel ()) in
    while (match peek () with TAmpersand -> true | _ -> false) do
      advance ();
      let r = parse_rel () in
      e := EBinop ("&", !e, r)
    done;
    !e

  and parse_bitxor () =
    let e = ref (parse_bitand ()) in
    while (match peek () with TCaret -> true | _ -> false) do
      advance ();
      let r = parse_bitand () in
      e := EBinop ("^", !e, r)
    done;
    !e

  and parse_bitor () =
    let e = ref (parse_bitxor ()) in
    while (match peek () with TPipe -> true | _ -> false) do
      advance ();
      let r = parse_bitxor () in
      e := EBinop ("|", !e, r)
    done;
    !e

  and parse_logand () =
    let e = ref (parse_bitor ()) in
    while (match peek () with TAnd -> true | _ -> false) do
      advance ();
      let r = parse_bitor () in
      e := EBinop ("&&", !e, r)
    done;
    !e

  and parse_logor () =
    let e = ref (parse_logand ()) in
    while (match peek () with TOr -> true | _ -> false) do
      advance ();
      let r = parse_logand () in
      e := EBinop ("||", !e, r)
    done;
    !e

  and parse_ternary () =
    let cond = parse_logor () in
    if peek () = TQuestion then begin
      advance ();
      let t = parse_ternary () in
      (match peek () with TColon -> advance () | _ -> ());
      let f = parse_ternary () in
      ETernary (cond, t, f)
    end else cond

  and parse_assignment () =
    let e = parse_ternary () in
    (match peek () with
    | TEq | TAddEq | TSubEq | TAndEq | TOrEq | TXorEq | TMulEq | TDivEq ->
        let (op,_,_) = consume () in
        let r = parse_assignment () in
        EBinop (tok_str op, e, r)
    | _ -> e)
  in

  let expr = parse_assignment () in
  (expr, !pos)

(* ─── Statement-level rewriter ───────────────────────────────────────────── *)

(** Detect if we're at a position that could start an expression statement.
    Rewrites expressions on the RHS of assignments and in return statements.
    Everything else is copied verbatim. *)
let rewrite_arithmetic_in_source ~prefix ~depth src =
  let toks = c_lex src in
  let n = Array.length toks in
  (* Reconstruct source character-by-character using token positions *)
  let src_len = String.length src in
  let out = Buffer.create (src_len * 2) in

  (* We process the source character stream, but consult the token array
     to know when we enter an expression context that can be obfuscated.
     Strategy:
       - Copy source verbatim until we find:
           • an assignment operator (=, +=, -=, &=, |=, ^=) — rewrite RHS
           • keyword 'return' — rewrite the expression after it
           • initialiser '= expr ;' in variable declarations
       - Inside the rewritten expr, MBA macros are inserted for + - ^ & |
       - String literals, comments, preprocessor lines: skip / copy verbatim
  *)

  (* We'll walk token by token and reconstruct the output by tracking
     "last character position emitted" *)
  let emitted_char_pos = ref 0 in

  let emit_raw_until char_end =
    if char_end > !emitted_char_pos && char_end <= src_len then begin
      Buffer.add_string out (String.sub src !emitted_char_pos (char_end - !emitted_char_pos));
      emitted_char_pos := char_end
    end
  in

  let tok_start idx =
    if idx < n then let (_,s,_) = toks.(idx) in s else src_len
  in
  let _tok_end idx =
    if idx < n then let (_,_,e) = toks.(idx) in e else src_len
  in

  let ti = ref 0 in

  while !ti < n - 1 (* skip final TEOF *) do
    let (tok, _ts, te) = toks.(!ti) in
    match tok with
    | TStrLit _ | TCharLit _ ->
        (* String/char literal or comment: copy verbatim *)
        emit_raw_until te;
        incr ti
    | TIdent "return" ->
        (* emit 'return' verbatim, then a mandatory space *)
        emit_raw_until te;
        incr ti;
        (* The next non-whitespace token starts the expression.
           We need to emit whitespace between 'return' and the expr. *)
        let expr_char_start = tok_start !ti in
        let ti_before_expr = !ti in
        let (expr, ti_after) = parse_expr toks !ti in
        let raw_end = tok_start ti_after in
        if ti_after > ti_before_expr then begin
          (* Emit the raw whitespace between 'return' and the first expr token
             so we get "return " not "return42" *)
          let ws = String.sub src te (expr_char_start - te) in
          let ws_trimmed = (* keep whitespace chars only *)
            String.concat "" (List.filter_map (fun c ->
              if c = ' ' || c = '\t' || c = '\n' || c = '\r'
              then Some (String.make 1 c)
              else None)
              (List.init (String.length ws) (String.get ws)))
          in
          Buffer.add_string out (if ws_trimmed = "" then " " else ws_trimmed);
          emitted_char_pos := expr_char_start;
          let rewritten = print_expr ~prefix ~depth ~mba:true expr in
          emitted_char_pos := raw_end;
          Buffer.add_string out rewritten;
          ti := ti_after
        end else
          incr ti
    | TEq | TAddEq | TSubEq | TAndEq | TOrEq | TXorEq | TMulEq | TDivEq ->
        (* emit the assignment operator verbatim *)
        emit_raw_until te;
        incr ti;
        (* Emit raw whitespace between operator and RHS token *)
        let expr_char_start = tok_start !ti in
        let ti_before_expr = !ti in
        let (expr, ti_after) = parse_expr toks !ti in
        let raw_end = tok_start ti_after in
        if ti_after > ti_before_expr then begin
          let ws = String.sub src te (expr_char_start - te) in
          Buffer.add_string out ws;
          emitted_char_pos := expr_char_start;
          let rewritten = print_expr ~prefix ~depth ~mba:true expr in
          emitted_char_pos := raw_end;
          Buffer.add_string out rewritten;
          ti := ti_after
        end else
          incr ti
    | _ ->
        (* copy verbatim *)
        emit_raw_until te;
        incr ti
  done;
  (* flush remainder *)
  emit_raw_until src_len;
  Buffer.contents out

(** Transform a complete C source code string *)
let obfuscate_source ?(config = default_config) src =
  let p = config.macro_prefix in
  (* Phase 1: Lift all if/else → nanomite dispatches *)
  let (lifted_src, nanomite_preamble) = lift_nanomites_in_source ~config src in

  (* Phase 3: Arithmetic expression rewriting (run on lifted source first,
     before the character-level string/comment pass, so the token lexer sees
     clean source rather than already-obfuscated string macros).
     Only applied when obfuscate_arithmetic is enabled. *)
  let arith_rewritten =
    if config.obfuscate_arithmetic then
      rewrite_arithmetic_in_source ~prefix:p ~depth:config.mba_depth lifted_src
    else
      lifted_src
  in

  let len = String.length arith_rewritten in
  let buf = Buffer.create (len * 2) in
  let seed_seq = ref config.seed in

  let next_seed () =
    seed_seq := xorshift32 !seed_seq;
    !seed_seq
  in

  (* File header *)
  Buffer.add_string buf "/* Protected by ASGARD-5877 C Macro Obfuscator */\n";
  Buffer.add_string buf "#include \"asgard_obf.h\"\n\n";
  (* Emit nanomite branch functions + auto-init constructor BEFORE the user source *)
  if nanomite_preamble <> "" then
    Buffer.add_string buf nanomite_preamble;

  (* Phase 2: String/constant obfuscation pass on the rewritten source *)
  let src = arith_rewritten in

  let i = ref 0 in
  while !i < len do
    let c = src.[!i] in
    if c = '/' && !i + 1 < len && src.[!i + 1] = '/' then begin
      (* Line comment: copy verbatim until newline *)
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i];
        incr i
      done
    end
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '*' then begin
      (* Block comment: copy verbatim *)
      Buffer.add_char buf src.[!i];
      Buffer.add_char buf src.[!i + 1];
      i := !i + 2;
      while !i + 1 < len && not (src.[!i] = '*' && src.[!i + 1] = '/') do
        Buffer.add_char buf src.[!i];
        incr i
      done;
      if !i + 1 < len then begin
        Buffer.add_char buf src.[!i];
        Buffer.add_char buf src.[!i + 1];
        i := !i + 2
      end
    end
    else if c = '#' then begin
      (* Preprocessor directive: copy entire line verbatim *)
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i];
        incr i
      done
    end
    else if c = '"' && config.obfuscate_strings then begin
      (* String literal *)
      incr i;
      let str_buf = Buffer.create 32 in
      let escaped = ref false in
      let closed = ref false in
      while !i < len && not !closed do
        let sc = src.[!i] in
        if !escaped then begin
          (match sc with
          | 'n' -> Buffer.add_char str_buf '\n'
          | 't' -> Buffer.add_char str_buf '\t'
          | 'r' -> Buffer.add_char str_buf '\r'
          | '\\' -> Buffer.add_char str_buf '\\'
          | '"' -> Buffer.add_char str_buf '"'
          | '0' -> Buffer.add_char str_buf '\000'
          | other ->
              Buffer.add_char str_buf '\\';
              Buffer.add_char str_buf other);
          escaped := false;
          incr i
        end
        else if sc = '\\' then begin
          escaped := true;
          incr i
        end
        else if sc = '"' then begin
          closed := true;
          incr i
        end
        else begin
          Buffer.add_char str_buf sc;
          incr i
        end
      done;
      let raw_str = Buffer.contents str_buf in
      let obf_str = obfuscate_string_literal ~prefix:p ~seed:(next_seed ()) raw_str in
      Buffer.add_string buf obf_str
    end
    else begin
      Buffer.add_char buf c;
      incr i
    end
  done;
  Buffer.contents buf

(** Transform a C source file on disk *)
let transform_file ?(config = default_config) ~in_file ~out_file ~header_file () =
  try
    let ensure_dir p =
      let d = Filename.dirname p in
      if d <> "" && d <> "." && not (Sys.file_exists d) then
        try Sys.mkdir d 0o755 with _ -> ()
    in
    ensure_dir out_file;
    (match header_file with Some h -> ensure_dir h | None -> ());

    let ic = open_in in_file in
    let len = in_channel_length ic in
    let content = really_input_string ic len in
    close_in ic;


    let obf_content = obfuscate_source ~config content in
    let oc = open_out out_file in
    output_string oc obf_content;
    close_out oc;

    (match header_file with
    | Some h_path ->
        let hoc = open_out h_path in
        output_string hoc (generate_header ~config ());
        close_out hoc
    | None -> ());

    Ok ()
  with exn ->
    Error (Printexc.to_string exn)
