(** C_macro_obf — C/C++ Preprocessor & Source-Level Macro Obfuscation Engine. *)

type config = {
  seed : int;
  mba_depth : int;
  obfuscate_strings : bool;
  obfuscate_constants : bool;
  obfuscate_arithmetic : bool;
  inject_opaque_predicates : bool;
  macro_prefix : string;
}

let default_config = {
  seed = 42;
  mba_depth = 2;
  obfuscate_strings = true;
  obfuscate_constants = true;
  obfuscate_arithmetic = true;
  inject_opaque_predicates = true;
  macro_prefix = "ASG_";
}

let xorshift32 seed =
  let x = ref (if seed = 0 then 0x1337BEEF else seed land 0x7FFFFFFF) in
  x := !x lxor (!x lsl 13);
  x := !x lxor (!x lsr 17);
  x := !x lxor (!x lsl 5);
  let res = !x land 0x7FFFFFFF in
  if res = 0 then 0x5A5A5A5A else res

let rand_u64 rng =
  let hi = Random.State.int64 rng 0x100000000L in
  let lo = Random.State.int64 rng 0x100000000L in
  Int64.logor (Int64.shift_left hi 32) lo

(** Generate standalone C/C++ header [asgard_obf.h] *)
let generate_header ?(config = default_config) () =
  let p = config.macro_prefix in
  let rng = Random.State.make [| config.seed |] in
  let _ = rng in
  let b = Buffer.create 4096 in
  let add s = Buffer.add_string b (s ^ "\n") in

  add "/* ========================================================================= */";
  add "/*  ASGARD-5877 Polymorphic C/C++ Obfuscation & Hardening Macro Header       */";
  add "/*  Auto-generated by Random_vISA / ASGARD-5877 Macro Obfuscation Engine     */";
  add "/* ========================================================================= */";
  add "#ifndef _ASGARD_OBF_H_";
  add "#define _ASGARD_OBF_H_";
  add "";
  add "#include <stdint.h>";
  add "#include <stddef.h>";
  add "#include <string.h>";
  add "";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add ("  #define " ^ p ^ "INLINE __attribute__((always_inline)) inline");
  add "#elif defined(_MSC_VER)";
  add ("  #define " ^ p ^ "INLINE __forceinline");
  add "#else";
  add ("  #define " ^ p ^ "INLINE inline");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 1. STACK STRING ENCRYPTION (Alloca / Compound Literal Decryption)         */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add ("#define " ^ p ^ "STR(enc_bytes, len, key) ({ \\");
  add "    static const uint8_t _enc[] = enc_bytes; \\";
  add "    char* _buf = (char*)__builtin_alloca((len) + 1); \\";
  add "    for (size_t _i = 0; _i < (size_t)(len); ++_i) { \\";
  add "        uint8_t _k = (uint8_t)(((uint32_t)(key) ^ (uint32_t)(_i * 0x5DU)) & 0xFFU); \\";
  add "        _buf[_i] = (char)(_enc[_i] ^ _k); \\";
  add "    } \\";
  add "    _buf[len] = '\\0'; \\";
  add "    _buf; \\";
  add "})";
  add "#else";
  add ("static " ^ p ^ "INLINE char* " ^ p ^ "decrypt_str(char* buf, const uint8_t* enc, size_t len, uint32_t key) {");
  add "    for (size_t i = 0; i < len; ++i) {";
  add "        uint8_t k = (uint8_t)((key ^ (uint32_t)(i * 0x5DU)) & 0xFFU);";
  add "        buf[i] = (char)(enc[i] ^ k);";
  add "    }";
  add "    buf[len] = '\\0';";
  add "    return buf;";
  add "}";
  add ("#define " ^ p ^ "STR(enc_bytes, len, key) \\");
  add ("    " ^ p ^ "decrypt_str((char*)alloca((len) + 1), (const uint8_t*)(enc_bytes), (len), (key))");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 2. MIXED BOOLEAN-ARITHMETIC (MBA) MACROS (Zhou / Eyrolles Identities)     */";
  add "/* ------------------------------------------------------------------------- */";
  add "/* Addition: x + y = (x ^ y) + 2*(x & y) */";
  add ("#define " ^ p ^ "MBA_ADD(a, b) (((a) ^ (b)) + 2 * ((a) & (b)))");
  add "";
  add "/* Subtraction: x - y = (x ^ y) - 2*(~x & y) */";
  add ("#define " ^ p ^ "MBA_SUB(a, b) (((a) ^ (b)) - 2 * ((~(a)) & (b)))");
  add "";
  add "/* Bitwise XOR: x ^ y = (x | y) - (x & y) */";
  add ("#define " ^ p ^ "MBA_XOR(a, b) (((a) | (b)) - ((a) & (b)))");
  add "";
  add "/* Bitwise AND: x & y = (x + y) - (x | y) */";
  add ("#define " ^ p ^ "MBA_AND(a, b) (((a) + (b)) - ((a) | (b)))");
  add "";
  add "/* Bitwise OR: x | y = (x ^ y) + (x & y) */";
  add ("#define " ^ p ^ "MBA_OR(a, b) (((a) ^ (b)) + ((a) & (b)))");
  add "";
  add "/* Bitwise NOT: ~x = x ^ 0xFFFFFFFFFFFFFFFFULL */";
  add ("#define " ^ p ^ "MBA_NOT(a) ((a) ^ 0xFFFFFFFFFFFFFFFFULL)");
  add "";
  add "/* Level 2 Nested MBA: x + y expanded through XOR and AND identities */";
  add ("#define " ^ p ^ "MBA_ADD_L2(a, b) (" ^ p ^ "MBA_XOR((a), (b)) + 2 * " ^ p ^ "MBA_AND((a), (b)))");
  add ("#define " ^ p ^ "MBA_SUB_L2(a, b) (" ^ p ^ "MBA_XOR((a), (b)) - 2 * " ^ p ^ "MBA_AND(" ^ p ^ "MBA_NOT(a), (b)))");
  add "";
  add "/* Non-Linear MBA (NLMBA): Non-linear cross-product expansion resisting 1-bit linear solvers (SiMBA/GAMBA) */";
  add ("#define " ^ p ^ "NLMBA_MUL(a, b) ((((a) & (b)) * ((a) | (b))) + (((a) & (~(b))) * ((~(a)) & (b))))");
  add ("#define " ^ p ^ "ZERO_INV1(a, b) ((((a) | (b)) + ((a) & (b))) - ((a) + (b)))");
  add ("#define " ^ p ^ "ZERO_INV2(a, b) (((a) ^ (b)) - (((a) | (b)) - ((a) & (b))))");
  add ("#define " ^ p ^ "ZERO_INV3(a, b) ((((a) & (b)) + ((a) & (~(b)))) - (a))");

  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 3. CONSTANT BLINDING MACROS                                              */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "BLIND_U64(c1, k1, k2) ((((uint64_t)(c1) ^ (uint64_t)(k1)) + (uint64_t)(k2)) - (uint64_t)(k2))");
  add ("#define " ^ p ^ "BLIND_I64(c1, k1, k2) ((int64_t)" ^ p ^ "BLIND_U64(c1, k1, k2))");
  add ("#define " ^ p ^ "BLIND_I32(c1, k1, k2) ((int32_t)" ^ p ^ "BLIND_U64(c1, k1, k2))");
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 4. NUMBER-THEORETIC OPAQUE PREDICATES                                    */";
  add "/* Invariants: for all x in Z, x*(x+1) % 2 == 0 and x^2 + x + 7 % 2 != 0    */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "OPAQUE_TRUE(x)  (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) == 0ULL)");
  add ("#define " ^ p ^ "OPAQUE_FALSE(x) (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) != 0ULL)");
  add ("#define " ^ p ^ "IF_OPAQUE(x, true_body, false_body) do { \\");
  add ("    if (" ^ p ^ "OPAQUE_TRUE(x)) { true_body; } else { false_body; } \\");
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 5. CONTROL-FLOW FLATTENING (CFF) PREPROCESSOR DSL                        */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "CFF_BEGIN(state_var, init_state) \\");
  add "    uint32_t state_var = (init_state); \\";
  add "    while (state_var != 0U) { \\";
  add "        switch (state_var) {";
  add "";
  add ("#define " ^ p ^ "CFF_STATE(state_id) case (state_id):");
  add "";
  add ("#define " ^ p ^ "CFF_NEXT(state_var, next_state) do { \\");
  add "    state_var = (next_state); \\";
  add "} while(0); break";
  add "";
  add ("#define " ^ p ^ "CFF_EXIT(state_var) do { \\");
  add "    state_var = 0U; \\";
  add "} while(0); break";
  add "";
  add ("#define " ^ p ^ "CFF_END() \\");
  add "        default: \\";
  add "            state_var = 0U; \\";
  add "            break; \\";
  add "        } \\";
  add "    }";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 6. MARKER-BASED REGION PROTECTION (VMProtect Style SDK)                   */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add "  #if defined(__arm64__) || defined(__aarch64__)";
  add "    #define ASGARD_BEGIN_VIRTUALIZE(tag) \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_BEG_V____\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_MUTATION(tag) \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_BEG_M____\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_ULTRA(tag) \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_BEG_U____\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "    #define ASGARD_END() \\";
  add "        __asm__ volatile (\"b 1f \\n\\t .ascii \\\"ASGARD_END______\\\" \\n\\t .balign 4 \\n 1:\\n\\t\")";
  add "  #else";
  add "    #define ASGARD_BEGIN_VIRTUALIZE(tag) \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_BEG_V__\\\" \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_MUTATION(tag) \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_BEG_M__\\\" \\n 1:\\n\\t\")";
  add "    #define ASGARD_BEGIN_ULTRA(tag) \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_BEG_U__\\\" \\n 1:\\n\\t\")";
  add "    #define ASGARD_END() \\";
  add "        __asm__ volatile (\"jmp 1f \\n\\t .ascii \\\"ASGARD_END____\\\" \\n 1:\\n\\t\")";
  add "  #endif";
  add "#else";
  add "  #define ASGARD_BEGIN_VIRTUALIZE(tag)";
  add "  #define ASGARD_BEGIN_MUTATION(tag)";
  add "  #define ASGARD_BEGIN_ULTRA(tag)";
  add "  #define ASGARD_END()";
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 7. COMPILE-TIME API HASHING & DYNAMIC RESOLUTION (IAT Elimination)        */";
  add "/* ------------------------------------------------------------------------- */";
  add ("static inline uint32_t " ^ p ^ "hash_api_str(const char* str) {");
  add "    uint32_t hash = 0x811C9DC5U;";
  add "    while (*str) {";
  add "        hash ^= (uint8_t)(*str++);";
  add "        hash *= 0x01000193U;";
  add "    }";
  add "    return hash;";
  add "}";
  add "";
  add "#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)";
  add "#include <dlfcn.h>";
  add ("static inline void* " ^ p ^ "resolve_api_by_hash(const char* const* known_symbols, size_t count, uint32_t target_hash) {");
  add "    for (size_t i = 0; i < count; ++i) {";
  add ("        if (" ^ p ^ "hash_api_str(known_symbols[i]) == target_hash) {");
  add "            return dlsym(RTLD_DEFAULT, known_symbols[i]);";
  add "        }";
  add "    }";
  add "    return (void*)0;";
  add "}";
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 8. HIGH-PRECISION ANTI-TRACE & HARDWARE TIMING WATCHDOG (RDTSC Guard)     */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__x86_64__) || defined(_M_X64)";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) {");
  add "    uint32_t lo, hi;";
  add "    __asm__ __volatile__(\"rdtsc\" : \"=a\"(lo), \"=d\"(hi));";
  add "    return (((uint64_t)hi) << 32) | (uint64_t)lo;";
  add "}";
  add "#elif defined(__aarch64__) || defined(__arm64__)";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) {");
  add "    uint64_t val;";
  add "    __asm__ __volatile__(\"mrs %0, cntvct_el0\" : \"=r\"(val));";
  add "    return val;";
  add "}";
  add "#else";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) { return 0ULL; }");
  add "#endif";
  add "";
  add ("#define " ^ p ^ "TIMING_GUARD_START(var_name) uint64_t var_name##_start = " ^ p ^ "read_cpu_ticks()");
  add ("#define " ^ p ^ "TIMING_GUARD_CHECK(var_name, max_ticks, on_tamper) do { \\");
  add ("    uint64_t var_name##_end = " ^ p ^ "read_cpu_ticks(); \\");
  add ("    if ((var_name##_end - var_name##_start) > (uint64_t)(max_ticks)) { \\");
  add "        on_tamper; \\";
  add "    } \\";
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 9. ACTIVE ANTI-DEBUGGING & HARDWARE BREAKPOINT PROBES (DR0..DR7 / sysctl) */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__APPLE__)";
  add "#include <sys/types.h>";
  add "#include <sys/sysctl.h>";
  add "#include <unistd.h>";
  add "#include <mach/mach.h>";
  add "#include <mach/thread_act.h>";
  add "";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) {");
  add "    int mib[4];";
  add "    struct kinfo_proc info;";
  add "    size_t size = sizeof(info);";
  add "    info.kp_proc.p_flag = 0;";
  add "    mib[0] = CTL_KERN;";
  add "    mib[1] = KERN_PROC;";
  add "    mib[2] = KERN_PROC_PID;";
  add "    mib[3] = getpid();";
  add "    if (sysctl(mib, 4, &info, &size, (void*)0, 0) == 0) {";
  add "        return (info.kp_proc.p_flag & P_TRACED) != 0;";
  add "    }";
  add "    return false;";
  add "}";
  add "";
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) {");
  add "#if defined(__x86_64__)";
  add "    x86_debug_state64_t dbg;";
  add "    mach_msg_type_number_t count = x86_DEBUG_STATE64_COUNT;";
  add "    if (thread_get_state(mach_thread_self(), x86_DEBUG_STATE64, (thread_state_t)&dbg, &count) == KERN_SUCCESS) {";
  add "        if (dbg.__dr0 || dbg.__dr1 || dbg.__dr2 || dbg.__dr3 || (dbg.__dr7 & 0xFF)) return true;";
  add "    }";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "    arm_debug_state64_t dbg;";
  add "    mach_msg_type_number_t count = ARM_DEBUG_STATE64_COUNT;";
  add "    if (thread_get_state(mach_thread_self(), ARM_DEBUG_STATE64, (thread_state_t)&dbg, &count) == KERN_SUCCESS) {";
  add "        for (int i = 0; i < 16; ++i) {";
  add "            if (dbg.__bvr[i] || (dbg.__bcr[i] & 1)) return true;";
  add "            if (dbg.__wvr[i] || (dbg.__wcr[i] & 1)) return true;";
  add "        }";
  add "    }";
  add "#endif";
  add "    return false;";
  add "}";
  add "#elif defined(__linux__)";
  add "#include <fcntl.h>";
  add "#include <unistd.h>";
  add "#include <string.h>";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) {");
  add "    int fd = open(\"/proc/self/status\", O_RDONLY);";
  add "    if (fd < 0) return false;";
  add "    char buf[512];";
  add "    ssize_t n = read(fd, buf, sizeof(buf) - 1);";
  add "    close(fd);";
  add "    if (n <= 0) return false;";
  add "    buf[n] = '\\0';";
  add "    const char* p_tracer = strstr(buf, \"TracerPid:\\t\");";
  add "    if (p_tracer) {";
  add "        p_tracer += 11;";
  add "        while (*p_tracer == ' ' || *p_tracer == '\\t') p_tracer++;";
  add "        if (*p_tracer > '0' && *p_tracer <= '9') return true;";
  add "    }";
  add "    return false;";
  add "}";
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) { return false; }");
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add "#include <windows.h>";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) { return IsDebuggerPresent(); }");
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) {");
  add "    CONTEXT ctx; memset(&ctx, 0, sizeof(ctx)); ctx.ContextFlags = CONTEXT_DEBUG_REGISTERS;";
  add "    if (GetThreadContext(GetCurrentThread(), &ctx)) {";
  add "        if (ctx.Dr0 || ctx.Dr1 || ctx.Dr2 || ctx.Dr3 || (ctx.Dr7 & 0xFF)) return true;";
  add "    }";
  add "    return false;";
  add "}";
  add "#else";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) { return false; }");
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) { return false; }");
  add "#endif";
  add "";
  add ("static inline bool " ^ p ^ "is_debugger_present(void) {");
  add ("    return " ^ p ^ "check_ptrace_sysctl() || " ^ p ^ "check_hw_breakpoints();");
  add "}";
  add "";
  add ("#define " ^ p ^ "ANTI_DEBUG_GUARD(on_debugger) do { \\");
  add ("    if (" ^ p ^ "is_debugger_present()) { \\");
  add "        on_debugger; \\";
  add "    } \\";
  add "} while(0)";
  add "";
  add "#endif /* _ASGARD_OBF_H_ */";


  Buffer.contents b


(** Obfuscate a raw string into an inline stack-decrypted C macro expression *)
let obfuscate_string_literal ~prefix ~seed s =
  let len = String.length s in
  let key = (xorshift32 (seed + len * 31)) land 0x7FFFFFFF in
  let bytes = Buffer.create (len * 6 + 10) in
  Buffer.add_string bytes "{ ";
  for i = 0 to len - 1 do
    let orig_byte = Char.code s.[i] in
    let k = ((key lxor (i * 0x5D)) land 0xFF) in
    let enc_byte = orig_byte lxor k in
    if i > 0 then Buffer.add_string bytes ", ";
    Buffer.add_string bytes (Printf.sprintf "0x%02X" enc_byte)
  done;
  if len = 0 then Buffer.add_string bytes "0x00";
  Buffer.add_string bytes " }";
  Printf.sprintf "%sSTR(((const uint8_t[])%s), %d, 0x%XU)" prefix (Buffer.contents bytes) len key

(** Obfuscate an integer constant *)
let obfuscate_constant_i64 ~prefix ~seed n =
  let rng = Random.State.make [| seed; Int64.to_int (Int64.logand n 0x7FFFFFFFL) |] in
  let k1 = rand_u64 rng in
  let k2 = rand_u64 rng in
  let c1 = Int64.logxor n k1 in
  Printf.sprintf "%sBLIND_I64(0x%LXULL, 0x%LXULL, 0x%LXULL)" prefix c1 k1 k2

(** Transform a complete C source code string *)
let obfuscate_source ?(config = default_config) src =
  let p = config.macro_prefix in
  let len = String.length src in
  let buf = Buffer.create (len * 2) in
  let seed_seq = ref config.seed in

  let next_seed () =
    seed_seq := xorshift32 !seed_seq;
    !seed_seq
  in

  Buffer.add_string buf "/* Protected by ASGARD-5877 C Macro Obfuscator */\n";
  Buffer.add_string buf "#include \"asgard_obf.h\"\n\n";

  let i = ref 0 in
  while !i < len do
    let c = src.[!i] in
    if c = '/' && !i + 1 < len && src.[!i + 1] = '/' then begin
      (* Line comment: copy verbatim until newline *)
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i];
        incr i
      done
    end
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '*' then begin
      (* Block comment: copy verbatim *)
      Buffer.add_char buf src.[!i];
      Buffer.add_char buf src.[!i + 1];
      i := !i + 2;
      while !i + 1 < len && not (src.[!i] = '*' && src.[!i + 1] = '/') do
        Buffer.add_char buf src.[!i];
        incr i
      done;
      if !i + 1 < len then begin
        Buffer.add_char buf src.[!i];
        Buffer.add_char buf src.[!i + 1];
        i := !i + 2
      end
    end
    else if c = '#' then begin
      (* Preprocessor directive: copy entire line verbatim *)
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i];
        incr i
      done
    end
    else if c = '"' && config.obfuscate_strings then begin
      (* String literal *)
      incr i;
      let str_buf = Buffer.create 32 in
      let escaped = ref false in
      let closed = ref false in
      while !i < len && not !closed do
        let sc = src.[!i] in
        if !escaped then begin
          (match sc with
          | 'n' -> Buffer.add_char str_buf '\n'
          | 't' -> Buffer.add_char str_buf '\t'
          | 'r' -> Buffer.add_char str_buf '\r'
          | '\\' -> Buffer.add_char str_buf '\\'
          | '"' -> Buffer.add_char str_buf '"'
          | '0' -> Buffer.add_char str_buf '\000'
          | other ->
              Buffer.add_char str_buf '\\';
              Buffer.add_char str_buf other);
          escaped := false;
          incr i
        end
        else if sc = '\\' then begin
          escaped := true;
          incr i
        end
        else if sc = '"' then begin
          closed := true;
          incr i
        end
        else begin
          Buffer.add_char str_buf sc;
          incr i
        end
      done;
      let raw_str = Buffer.contents str_buf in
      let obf_str = obfuscate_string_literal ~prefix:p ~seed:(next_seed ()) raw_str in
      Buffer.add_string buf obf_str
    end
    else begin
      Buffer.add_char buf c;
      incr i
    end
  done;
  Buffer.contents buf

(** Transform a C source file on disk *)
let transform_file ?(config = default_config) ~in_file ~out_file ~header_file () =
  try
    let ensure_dir p =
      let d = Filename.dirname p in
      if d <> "" && d <> "." && not (Sys.file_exists d) then
        try Sys.mkdir d 0o755 with _ -> ()
    in
    ensure_dir out_file;
    (match header_file with Some h -> ensure_dir h | None -> ());

    let ic = open_in in_file in
    let len = in_channel_length ic in
    let content = really_input_string ic len in
    close_in ic;


    let obf_content = obfuscate_source ~config content in
    let oc = open_out out_file in
    output_string oc obf_content;
    close_out oc;

    (match header_file with
    | Some h_path ->
        let hoc = open_out h_path in
        output_string hoc (generate_header ~config ());
        close_out hoc
    | None -> ());

    Ok ()
  with exn ->
    Error (Printexc.to_string exn)
