(** C_macro_obf — C/C++ Preprocessor & Source-Level Macro Obfuscation Engine. *)

type config = {
  seed : int;
  mba_depth : int;
  obfuscate_strings : bool;
  obfuscate_constants : bool;
  obfuscate_arithmetic : bool;
  inject_opaque_predicates : bool;
  macro_prefix : string;
}

let default_config = {
  seed = 42;
  mba_depth = 2;
  obfuscate_strings = true;
  obfuscate_constants = true;
  obfuscate_arithmetic = true;
  inject_opaque_predicates = true;
  macro_prefix = "ASG_";
}

let xorshift32 seed =
  let x = ref (if seed = 0 then 0x1337BEEF else seed land 0x7FFFFFFF) in
  x := !x lxor (!x lsl 13);
  x := !x lxor (!x lsr 17);
  x := !x lxor (!x lsl 5);
  let res = !x land 0x7FFFFFFF in
  if res = 0 then 0x5A5A5A5A else res

let rand_u64 rng =
  let hi = Random.State.int64 rng 0x100000000L in
  let lo = Random.State.int64 rng 0x100000000L in
  Int64.logor (Int64.shift_left hi 32) lo

(** Generate standalone C/C++ header [asgard_obf.h] *)
let generate_header ?(config = default_config) () =
  let p = config.macro_prefix in
  let rng = Random.State.make [| config.seed |] in
  let _ = rng in
  let b = Buffer.create 4096 in
  let add s = Buffer.add_string b (s ^ "\n") in

  add "/* ========================================================================= */";
  add "/*  ASGARD-5877 Polymorphic C/C++ Obfuscation & Hardening Macro Header       */";
  add "/*  Auto-generated by Random_vISA / ASGARD-5877 Macro Obfuscation Engine     */";
  add "/* ========================================================================= */";
  add "#ifndef _ASGARD_OBF_H_";
  add "#define _ASGARD_OBF_H_";
  add "";
  add "#include <stdint.h>";
  add "#include <stddef.h>";
  add "#include <string.h>";
  add "";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add ("  #define " ^ p ^ "INLINE __attribute__((always_inline)) inline");
  add "#elif defined(_MSC_VER)";
  add ("  #define " ^ p ^ "INLINE __forceinline");
  add "#else";
  add ("  #define " ^ p ^ "INLINE inline");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 1. STACK STRING ENCRYPTION (Alloca / Compound Literal Decryption)         */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__GNUC__) || defined(__clang__)";
  add ("#define " ^ p ^ "STR(enc_bytes, len, key) ({ \\");
  add "    static const uint8_t _enc[] = enc_bytes; \\";
  add "    char* _buf = (char*)__builtin_alloca((len) + 1); \\";
  add "    for (size_t _i = 0; _i < (size_t)(len); ++_i) { \\";
  add "        uint8_t _k = (uint8_t)(((uint32_t)(key) ^ (uint32_t)(_i * 0x5DU)) & 0xFFU); \\";
  add "        _buf[_i] = (char)(_enc[_i] ^ _k); \\";
  add "    } \\";
  add "    _buf[len] = '\\0'; \\";
  add "    _buf; \\";
  add "})";
  add "#else";
  add ("static " ^ p ^ "INLINE char* " ^ p ^ "decrypt_str(char* buf, const uint8_t* enc, size_t len, uint32_t key) {");
  add "    for (size_t i = 0; i < len; ++i) {";
  add "        uint8_t k = (uint8_t)((key ^ (uint32_t)(i * 0x5DU)) & 0xFFU);";
  add "        buf[i] = (char)(enc[i] ^ k);";
  add "    }";
  add "    buf[len] = '\\0';";
  add "    return buf;";
  add "}";
  add ("#define " ^ p ^ "STR(enc_bytes, len, key) \\");
  add ("    " ^ p ^ "decrypt_str((char*)alloca((len) + 1), (const uint8_t*)(enc_bytes), (len), (key))");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 2. MIXED BOOLEAN-ARITHMETIC (MBA) MACROS (Zhou / Eyrolles Identities)     */";
  add "/* ------------------------------------------------------------------------- */";
  add "/* Addition: x + y = (x ^ y) + 2*(x & y) */";
  add ("#define " ^ p ^ "MBA_ADD(a, b) (((a) ^ (b)) + 2 * ((a) & (b)))");
  add "";
  add "/* Subtraction: x - y = (x ^ y) - 2*(~x & y) */";
  add ("#define " ^ p ^ "MBA_SUB(a, b) (((a) ^ (b)) - 2 * ((~(a)) & (b)))");
  add "";
  add "/* Bitwise XOR: x ^ y = (x | y) - (x & y) */";
  add ("#define " ^ p ^ "MBA_XOR(a, b) (((a) | (b)) - ((a) & (b)))");
  add "";
  add "/* Bitwise AND: x & y = (x + y) - (x | y) */";
  add ("#define " ^ p ^ "MBA_AND(a, b) (((a) + (b)) - ((a) | (b)))");
  add "";
  add "/* Bitwise OR: x | y = (x ^ y) + (x & y) */";
  add ("#define " ^ p ^ "MBA_OR(a, b) (((a) ^ (b)) + ((a) & (b)))");
  add "";
  add "/* Bitwise NOT: ~x = x ^ 0xFFFFFFFFFFFFFFFFULL */";
  add ("#define " ^ p ^ "MBA_NOT(a) ((a) ^ 0xFFFFFFFFFFFFFFFFULL)");
  add "";
  add "/* Level 2 Nested MBA: x + y expanded through XOR and AND identities */";
  add ("#define " ^ p ^ "MBA_ADD_L2(a, b) (" ^ p ^ "MBA_XOR((a), (b)) + 2 * " ^ p ^ "MBA_AND((a), (b)))");
  add ("#define " ^ p ^ "MBA_SUB_L2(a, b) (" ^ p ^ "MBA_XOR((a), (b)) - 2 * " ^ p ^ "MBA_AND(" ^ p ^ "MBA_NOT(a), (b)))");
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 3. CONSTANT BLINDING MACROS                                              */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "BLIND_U64(c1, k1, k2) ((((uint64_t)(c1) ^ (uint64_t)(k1)) + (uint64_t)(k2)) - (uint64_t)(k2))");
  add ("#define " ^ p ^ "BLIND_I64(c1, k1, k2) ((int64_t)" ^ p ^ "BLIND_U64(c1, k1, k2))");
  add ("#define " ^ p ^ "BLIND_I32(c1, k1, k2) ((int32_t)" ^ p ^ "BLIND_U64(c1, k1, k2))");
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 4. NUMBER-THEORETIC OPAQUE PREDICATES                                    */";
  add "/* Invariants: for all x in Z, x*(x+1) % 2 == 0 and x^2 + x + 7 % 2 != 0    */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "OPAQUE_TRUE(x)  (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) == 0ULL)");
  add ("#define " ^ p ^ "OPAQUE_FALSE(x) (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) != 0ULL)");
  add ("#define " ^ p ^ "IF_OPAQUE(x, true_body, false_body) do { \\");
  add ("    if (" ^ p ^ "OPAQUE_TRUE(x)) { true_body; } else { false_body; } \\");
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 5. CONTROL-FLOW FLATTENING (CFF) PREPROCESSOR DSL                        */";
  add "/* ------------------------------------------------------------------------- */";
  add ("#define " ^ p ^ "CFF_BEGIN(state_var, init_state) \\");
  add "    uint32_t state_var = (init_state); \\";
  add "    while (state_var != 0U) { \\";
  add "        switch (state_var) {";
  add "";
  add ("#define " ^ p ^ "CFF_STATE(state_id) case (state_id):");
  add "";
  add ("#define " ^ p ^ "CFF_NEXT(state_var, next_state) do { \\");
  add "    state_var = (next_state); \\";
  add "} while(0); break";
  add "";
  add ("#define " ^ p ^ "CFF_EXIT(state_var) do { \\");
  add "    state_var = 0U; \\";
  add "} while(0); break";
  add "";
  add ("#define " ^ p ^ "CFF_END() \\");
  add "        default: \\";
  add "            state_var = 0U; \\";
  add "            break; \\";
  add "        } \\";
  add "    }";
  add "";
  add "#endif /* _ASGARD_OBF_H_ */";
  Buffer.contents b

(** Obfuscate a raw string into an inline stack-decrypted C macro expression *)
let obfuscate_string_literal ~prefix ~seed s =
  let len = String.length s in
  let key = (xorshift32 (seed + len * 31)) land 0x7FFFFFFF in
  let bytes = Buffer.create (len * 6 + 10) in
  Buffer.add_string bytes "{ ";
  for i = 0 to len - 1 do
    let orig_byte = Char.code s.[i] in
    let k = ((key lxor (i * 0x5D)) land 0xFF) in
    let enc_byte = orig_byte lxor k in
    if i > 0 then Buffer.add_string bytes ", ";
    Buffer.add_string bytes (Printf.sprintf "0x%02X" enc_byte)
  done;
  if len = 0 then Buffer.add_string bytes "0x00";
  Buffer.add_string bytes " }";
  Printf.sprintf "%sSTR(((const uint8_t[])%s), %d, 0x%XU)" prefix (Buffer.contents bytes) len key

(** Obfuscate an integer constant *)
let obfuscate_constant_i64 ~prefix ~seed n =
  let rng = Random.State.make [| seed; Int64.to_int (Int64.logand n 0x7FFFFFFFL) |] in
  let k1 = rand_u64 rng in
  let k2 = rand_u64 rng in
  let c1 = Int64.logxor n k1 in
  Printf.sprintf "%sBLIND_I64(0x%LXULL, 0x%LXULL, 0x%LXULL)" prefix c1 k1 k2

(** Transform a complete C source code string *)
let obfuscate_source ?(config = default_config) src =
  let p = config.macro_prefix in
  let len = String.length src in
  let buf = Buffer.create (len * 2) in
  let seed_seq = ref config.seed in

  let next_seed () =
    seed_seq := xorshift32 !seed_seq;
    !seed_seq
  in

  Buffer.add_string buf "/* Protected by ASGARD-5877 C Macro Obfuscator */\n";
  Buffer.add_string buf "#include \"asgard_obf.h\"\n\n";

  let i = ref 0 in
  while !i < len do
    let c = src.[!i] in
    if c = '/' && !i + 1 < len && src.[!i + 1] = '/' then begin
      (* Line comment: copy verbatim until newline *)
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i];
        incr i
      done
    end
    else if c = '/' && !i + 1 < len && src.[!i + 1] = '*' then begin
      (* Block comment: copy verbatim *)
      Buffer.add_char buf src.[!i];
      Buffer.add_char buf src.[!i + 1];
      i := !i + 2;
      while !i + 1 < len && not (src.[!i] = '*' && src.[!i + 1] = '/') do
        Buffer.add_char buf src.[!i];
        incr i
      done;
      if !i + 1 < len then begin
        Buffer.add_char buf src.[!i];
        Buffer.add_char buf src.[!i + 1];
        i := !i + 2
      end
    end
    else if c = '#' then begin
      (* Preprocessor directive: copy entire line verbatim *)
      while !i < len && src.[!i] <> '\n' do
        Buffer.add_char buf src.[!i];
        incr i
      done
    end
    else if c = '"' && config.obfuscate_strings then begin
      (* String literal *)
      incr i;
      let str_buf = Buffer.create 32 in
      let escaped = ref false in
      let closed = ref false in
      while !i < len && not !closed do
        let sc = src.[!i] in
        if !escaped then begin
          (match sc with
          | 'n' -> Buffer.add_char str_buf '\n'
          | 't' -> Buffer.add_char str_buf '\t'
          | 'r' -> Buffer.add_char str_buf '\r'
          | '\\' -> Buffer.add_char str_buf '\\'
          | '"' -> Buffer.add_char str_buf '"'
          | '0' -> Buffer.add_char str_buf '\000'
          | other ->
              Buffer.add_char str_buf '\\';
              Buffer.add_char str_buf other);
          escaped := false;
          incr i
        end
        else if sc = '\\' then begin
          escaped := true;
          incr i
        end
        else if sc = '"' then begin
          closed := true;
          incr i
        end
        else begin
          Buffer.add_char str_buf sc;
          incr i
        end
      done;
      let raw_str = Buffer.contents str_buf in
      let obf_str = obfuscate_string_literal ~prefix:p ~seed:(next_seed ()) raw_str in
      Buffer.add_string buf obf_str
    end
    else begin
      Buffer.add_char buf c;
      incr i
    end
  done;
  Buffer.contents buf

(** Transform a C source file on disk *)
let transform_file ?(config = default_config) ~in_file ~out_file ~header_file () =
  try
    let ensure_dir p =
      let d = Filename.dirname p in
      if d <> "" && d <> "." && not (Sys.file_exists d) then
        try Sys.mkdir d 0o755 with _ -> ()
    in
    ensure_dir out_file;
    (match header_file with Some h -> ensure_dir h | None -> ());

    let ic = open_in in_file in
    let len = in_channel_length ic in
    let content = really_input_string ic len in
    close_in ic;


    let obf_content = obfuscate_source ~config content in
    let oc = open_out out_file in
    output_string oc obf_content;
    close_out oc;

    (match header_file with
    | Some h_path ->
        let hoc = open_out h_path in
        output_string hoc (generate_header ~config ());
        close_out hoc
    | None -> ());

    Ok ()
  with exn ->
    Error (Printexc.to_string exn)
