let emit_guards_macros b ~p =
  let add s = Buffer.add_string b (s ^ "\n") in
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 8. HIGH-PRECISION ANTI-TRACE & HARDWARE TIMING WATCHDOG (RDTSC Guard)     */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__x86_64__) || defined(_M_X64)";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) {");
  add "    uint32_t lo, hi;";
  add "    __asm__ __volatile__(\"rdtsc\" : \"=a\"(lo), \"=d\"(hi));";
  add "    return (((uint64_t)hi) << 32) | (uint64_t)lo;";
  add "}";
  add "#elif defined(__aarch64__) || defined(__arm64__)";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) {");
  add "    uint64_t val;";
  add "    __asm__ __volatile__(\"mrs %0, cntvct_el0\" : \"=r\"(val));";
  add "    return val;";
  add "}";
  add "#else";
  add ("static inline uint64_t " ^ p ^ "read_cpu_ticks(void) { return 0ULL; }");
  add "#endif";
  add "";
  add ("#define " ^ p ^ "TIMING_GUARD_START(var_name) uint64_t var_name##_start = " ^ p ^ "read_cpu_ticks()");
  add ("#define " ^ p ^ "TIMING_GUARD_CHECK(var_name, max_ticks, on_tamper) do { \\");
  add ("    uint64_t var_name##_end = " ^ p ^ "read_cpu_ticks(); \\");
  add ("    if ((var_name##_end - var_name##_start) > (uint64_t)(max_ticks)) { \\");
  add "        on_tamper; \\";
  add "    } \\";
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 9. ACTIVE ANTI-DEBUGGING & HARDWARE BREAKPOINT PROBES (DR0..DR7 / sysctl) */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if defined(__APPLE__)";
  add "#include <sys/types.h>";
  add "#include <sys/sysctl.h>";
  add "#include <unistd.h>";
  add "#include <mach/mach.h>";
  add "#include <mach/thread_act.h>";
  add "";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) {");
  add "    int mib[4];";
  add "    struct kinfo_proc info;";
  add "    size_t size = sizeof(info);";
  add "    info.kp_proc.p_flag = 0;";
  add "    mib[0] = CTL_KERN;";
  add "    mib[1] = KERN_PROC;";
  add "    mib[2] = KERN_PROC_PID;";
  add "    mib[3] = getpid();";
  add "    if (sysctl(mib, 4, &info, &size, (void*)0, 0) == 0) {";
  add "        return (info.kp_proc.p_flag & P_TRACED) != 0;";
  add "    }";
  add "    return false;";
  add "}";
  add "";
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) {");
  add "#if defined(__x86_64__)";
  add "    x86_debug_state64_t dbg;";
  add "    mach_msg_type_number_t count = x86_DEBUG_STATE64_COUNT;";
  add "    if (thread_get_state(mach_thread_self(), x86_DEBUG_STATE64, (thread_state_t)&dbg, &count) == KERN_SUCCESS) {";
  add "        if (dbg.__dr0 || dbg.__dr1 || dbg.__dr2 || dbg.__dr3 || (dbg.__dr7 & 0xFF)) return true;";
  add "    }";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "    arm_debug_state64_t dbg;";
  add "    mach_msg_type_number_t count = ARM_DEBUG_STATE64_COUNT;";
  add "    if (thread_get_state(mach_thread_self(), ARM_DEBUG_STATE64, (thread_state_t)&dbg, &count) == KERN_SUCCESS) {";
  add "        for (int i = 0; i < 16; ++i) {";
  add "            if (dbg.__bvr[i] || (dbg.__bcr[i] & 1)) return true;";
  add "            if (dbg.__wvr[i] || (dbg.__wcr[i] & 1)) return true;";
  add "        }";
  add "    }";
  add "#endif";
  add "    return false;";
  add "}";
  add "#elif defined(__linux__)";
  add "#include <fcntl.h>";
  add "#include <unistd.h>";
  add "#include <string.h>";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) {");
  add "    int fd = open(\"/proc/self/status\", O_RDONLY);";
  add "    if (fd < 0) return false;";
  add "    char buf[512];";
  add "    ssize_t n = read(fd, buf, sizeof(buf) - 1);";
  add "    close(fd);";
  add "    if (n <= 0) return false;";
  add "    buf[n] = '\\0';";
  add "    const char* p_tracer = strstr(buf, \"TracerPid:\\t\");";
  add "    if (p_tracer) {";
  add "        p_tracer += 11;";
  add "        while (*p_tracer == ' ' || *p_tracer == '\\t') p_tracer++;";
  add "        if (*p_tracer > '0' && *p_tracer <= '9') return true;";
  add "    }";
  add "    return false;";
  add "}";
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) { return false; }");
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add "#include <windows.h>";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) { return IsDebuggerPresent(); }");
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) {");
  add "    CONTEXT ctx; memset(&ctx, 0, sizeof(ctx)); ctx.ContextFlags = CONTEXT_DEBUG_REGISTERS;";
  add "    if (GetThreadContext(GetCurrentThread(), &ctx)) {";
  add "        if (ctx.Dr0 || ctx.Dr1 || ctx.Dr2 || ctx.Dr3 || (ctx.Dr7 & 0xFF)) return true;";
  add "    }";
  add "    return false;";
  add "}";
  add "#else";
  add ("static inline bool " ^ p ^ "check_ptrace_sysctl(void) { return false; }");
  add ("static inline bool " ^ p ^ "check_hw_breakpoints(void) { return false; }");
  add "#endif";
  add "";
  add ("static inline bool " ^ p ^ "is_debugger_present(void) {");
  add ("    return " ^ p ^ "check_ptrace_sysctl() || " ^ p ^ "check_hw_breakpoints();");
  add "}";
  add "";
  add ("#define " ^ p ^ "ANTI_DEBUG_GUARD(on_debugger) do { \\");
  add ("    if (" ^ p ^ "is_debugger_present()) { \\");
  add "        on_debugger; \\";
  add "    } \\";
  add "} while(0)";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 10. OPAQUE SIGNAL & EXCEPTION-BASED DISPATCHING (ucontext_t / SEH)        */";
  add "/* ------------------------------------------------------------------------- */";
  add "#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)";
  add "#include <signal.h>";
  add "#if defined(__APPLE__)";
  add "#include <sys/ucontext.h>";
  add "#else";
  add "#include <ucontext.h>";
  add "#endif";
  add "#include <string.h>";
  add "";
  add ("static volatile uintptr_t " ^ p ^ "sig_target = 0;");
  add "";
  add ("static void " ^ p ^ "signal_dispatcher_handler(int sig, siginfo_t* info, void* ucontext_ptr) {");
  add "    (void)sig;";
  add "    (void)info;";
  add ("    if (" ^ p ^ "sig_target != 0) {");
  add "        ucontext_t* uc = (ucontext_t*)ucontext_ptr;";
  add "#if defined(__APPLE__)";
  add "#if defined(__x86_64__)";
  add ("        uc->uc_mcontext->__ss.__rip = " ^ p ^ "sig_target;");
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add ("        uc->uc_mcontext->__ss.__pc = " ^ p ^ "sig_target;");
  add "#endif";
  add "#elif defined(__linux__)";
  add "#if defined(__x86_64__)";
  add ("        uc->uc_mcontext.gregs[REG_RIP] = (greg_t)" ^ p ^ "sig_target;");
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add ("        uc->uc_mcontext.pc = " ^ p ^ "sig_target;");
  add "#endif";
  add "#endif";
  add ("        " ^ p ^ "sig_target = 0;");
  add "    }";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_signal_dispatcher(void) {");
  add "    struct sigaction sa;";
  add "    memset(&sa, 0, sizeof(sa));";
  add ("    sa.sa_sigaction = " ^ p ^ "signal_dispatcher_handler;");
  add "    sa.sa_flags = SA_SIGINFO;";
  add "    sigemptyset(&sa.sa_mask);";
  add "    sigaction(SIGFPE, &sa, NULL);";
  add "    sigaction(SIGILL, &sa, NULL);";
  add "}";
  add "";
  add ("#define " ^ p ^ "SIG_DISPATCH_SETUP() " ^ p ^ "install_signal_dispatcher()");
  add ("#define " ^ p ^ "SIG_JUMP(target_ptr) do { \\");
  add ("    " ^ p ^ "sig_target = (uintptr_t)(target_ptr); \\");
  add "    raise(SIGILL); \\";
  add "} while(0)";
  add "";
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add "#include <windows.h>";
  add ("static volatile uintptr_t " ^ p ^ "sig_target = 0;");
  add "";
  add ("static LONG WINAPI " ^ p ^ "veh_handler(PEXCEPTION_POINTERS pExceptionInfo) {");
  add ("    if (" ^ p ^ "sig_target != 0) {");
  add "#if defined(_M_X64) || defined(__x86_64__)";
  add ("        pExceptionInfo->ContextRecord->Rip = (DWORD64)" ^ p ^ "sig_target;");
  add "#else";
  add ("        pExceptionInfo->ContextRecord->Eip = (DWORD)" ^ p ^ "sig_target;");
  add "#endif";
  add ("        " ^ p ^ "sig_target = 0;");
  add "        return EXCEPTION_CONTINUE_EXECUTION;";
  add "    }";
  add "    return EXCEPTION_CONTINUE_SEARCH;";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_signal_dispatcher(void) {");
  add ("    AddVectoredExceptionHandler(1, " ^ p ^ "veh_handler);");
  add "}";
  add "";
  add ("#define " ^ p ^ "SIG_DISPATCH_SETUP() " ^ p ^ "install_signal_dispatcher()");
  add ("#define " ^ p ^ "SIG_JUMP(target_ptr) do { \\");
  add ("    " ^ p ^ "sig_target = (uintptr_t)(target_ptr); \\");
  add "    RaiseException(0xE0000001, 0, 0, NULL); \\";
  add "} while(0)";
  add "#else";
  add ("#define " ^ p ^ "SIG_DISPATCH_SETUP() ((void)0)");
  add ("#define " ^ p ^ "SIG_JUMP(target_ptr) ((void)0)");
  add "#endif";
  add "";
  add "/* ------------------------------------------------------------------------- */";
  add "/* 11. MULTITHREADED NANOMITES & TRAP-AND-TRACE DISPATCHING                  */";
  add "/* ------------------------------------------------------------------------- */";
  add "typedef struct {";
  add "    uint32_t trap_id;";
  add "    uintptr_t target_true;";
  add "    uintptr_t target_false;";
  add "    uint32_t key;";
  add ("} " ^ p ^ "nanomite_entry_t;");
  add "";
  add ("static " ^ p ^ "nanomite_entry_t " ^ p ^ "nanomite_table[64];");
  add ("static size_t " ^ p ^ "nanomite_count = 0;");
  add ("static volatile uint32_t " ^ p ^ "current_trap_id = 0;");
  add ("static volatile uint32_t " ^ p ^ "current_condition = 0;");
  add "";
  add ("static inline void " ^ p ^ "register_nanomite(uint32_t trap_id, uintptr_t t_true, uintptr_t t_false, uint32_t key) {");
  add ("    if (" ^ p ^ "nanomite_count < 64) {");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].trap_id = trap_id;");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].target_true = t_true ^ (uintptr_t)key;");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].target_false = t_false ^ (uintptr_t)key;");
  add ("        " ^ p ^ "nanomite_table[" ^ p ^ "nanomite_count].key = key;");
  add ("        " ^ p ^ "nanomite_count++;");
  add "    }";
  add "}";
  add "";
  add "#if (defined(__APPLE__) || defined(__linux__)) && !defined(_MSC_VER)";
  add ("static void " ^ p ^ "nanomite_trap_handler(int sig, siginfo_t* info, void* ucontext_ptr) {");
  add "    (void)sig; (void)info;";
  add "    ucontext_t* uc = (ucontext_t*)ucontext_ptr;";
  add ("    for (size_t i = 0; i < " ^ p ^ "nanomite_count; ++i) {");
  add ("        if (" ^ p ^ "nanomite_table[i].trap_id == " ^ p ^ "current_trap_id) {");
  add ("            uintptr_t enc_target = " ^ p ^ "current_condition ?");
  add ("                " ^ p ^ "nanomite_table[i].target_true :");
  add ("                " ^ p ^ "nanomite_table[i].target_false;");
  add ("            uintptr_t real_target = enc_target ^ (uintptr_t)" ^ p ^ "nanomite_table[i].key;");
  add "#if defined(__APPLE__)";
  add "#if defined(__x86_64__)";
  add "            uc->uc_mcontext->__ss.__rip = real_target;";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "            uc->uc_mcontext->__ss.__pc = real_target;";
  add "#endif";
  add "#elif defined(__linux__)";
  add "#if defined(__x86_64__)";
  add "            uc->uc_mcontext.gregs[REG_RIP] = (greg_t)real_target;";
  add "#elif defined(__arm64__) || defined(__aarch64__)";
  add "            uc->uc_mcontext.pc = real_target;";
  add "#endif";
  add "#endif";
  add ("            " ^ p ^ "current_trap_id = 0;");
  add "            return;";
  add "        }";
  add "    }";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_nanomites(void) {");
  add "    struct sigaction sa;";
  add "    memset(&sa, 0, sizeof(sa));";
  add ("    sa.sa_sigaction = " ^ p ^ "nanomite_trap_handler;");
  add "    sa.sa_flags = SA_SIGINFO;";
  add "    sigemptyset(&sa.sa_mask);";
  add "    sigaction(SIGTRAP, &sa, NULL);";
  add "}";
  add "";
  add ("#define " ^ p ^ "NANOMITE_INIT() " ^ p ^ "install_nanomites()");
  add ("#define " ^ p ^ "NANOMITE_REGISTER(id, t_true, t_false, key) " ^ p ^ "register_nanomite((id), (uintptr_t)(t_true), (uintptr_t)(t_false), (uint32_t)(key))");
  add ("#define " ^ p ^ "NANOMITE_DISPATCH(id, cond) do { \\");
  add ("    " ^ p ^ "current_trap_id = (id); \\");
  add ("    " ^ p ^ "current_condition = (cond) ? 1 : 0; \\");
  add "    raise(SIGTRAP); \\";
  add "} while(0)";
  add "#elif defined(_WIN32) || defined(_WIN64)";
  add ("static LONG WINAPI " ^ p ^ "nanomite_veh_handler(PEXCEPTION_POINTERS pExceptionInfo) {");
  add "    if (pExceptionInfo->ExceptionRecord->ExceptionCode == EXCEPTION_BREAKPOINT || pExceptionInfo->ExceptionRecord->ExceptionCode == 0xE0000002) {";
  add ("        for (size_t i = 0; i < " ^ p ^ "nanomite_count; ++i) {");
  add ("            if (" ^ p ^ "nanomite_table[i].trap_id == " ^ p ^ "current_trap_id) {");
  add ("                uintptr_t enc_target = " ^ p ^ "current_condition ?");
  add ("                    " ^ p ^ "nanomite_table[i].target_true :");
  add ("                    " ^ p ^ "nanomite_table[i].target_false;");
  add ("                uintptr_t real_target = enc_target ^ (uintptr_t)" ^ p ^ "nanomite_table[i].key;");
  add "#if defined(_M_X64) || defined(__x86_64__)";
  add "                pExceptionInfo->ContextRecord->Rip = (DWORD64)real_target;";
  add "#else";
  add "                pExceptionInfo->ContextRecord->Eip = (DWORD)real_target;";
  add "#endif";
  add ("                " ^ p ^ "current_trap_id = 0;");
  add "                return EXCEPTION_CONTINUE_EXECUTION;";
  add "            }";
  add "        }";
  add "    }";
  add "    return EXCEPTION_CONTINUE_SEARCH;";
  add "}";
  add "";
  add ("static inline void " ^ p ^ "install_nanomites(void) {");
  add ("    AddVectoredExceptionHandler(1, " ^ p ^ "nanomite_veh_handler);");
  add "}";
  add "";
  add ("#define " ^ p ^ "NANOMITE_INIT() " ^ p ^ "install_nanomites()");
  add ("#define " ^ p ^ "NANOMITE_REGISTER(id, t_true, t_false, key) " ^ p ^ "register_nanomite((id), (uintptr_t)(t_true), (uintptr_t)(t_false), (uint32_t)(key))");
  add ("#define " ^ p ^ "NANOMITE_DISPATCH(id, cond) do { \\");
  add ("    " ^ p ^ "current_trap_id = (id); \\");
  add ("    " ^ p ^ "current_condition = (cond) ? 1 : 0; \\");
  add "    RaiseException(0xE0000002, 0, 0, NULL); \\";
  add "} while(0)";
  add "#else";
  add ("#define " ^ p ^ "NANOMITE_INIT() ((void)0)");
  add ("#define " ^ p ^ "NANOMITE_REGISTER(id, t_true, t_false, key) ((void)0)");
  add ("#define " ^ p ^ "NANOMITE_DISPATCH(id, cond) ((void)0)");
  add "#endif";
  add "";
  add "#endif /* _ASGARD_OBF_H_ */"
