(** High-Throughput Apple Metal GPU MBA Synthesis & Obfuscation Engine.

    Eliminates CPU e-graph bottlenecks by querying Metal compute shaders for
    hundreds of mathematically verified non-linear MBA solution seeds in < 2ms,
    then lowering them into SiMBA-resistant VM-IR instruction sequences. *)

open Vm_ir

type gpu_mba_pool

(** [create_pool ?seed ?max_results ~rng ()]
    queries Apple Metal GPU (65,536 threads) for a batch of verified non-linear
    MBA solution seeds. Falls back gracefully to deterministic PRNG if GPU is
    unavailable. *)
val create_pool :
  ?seed:int64 ->
  ?max_results:int ->
  rng:Random.State.t ->
  unit ->
  gpu_mba_pool

(** Returns the number of solution seeds in the pool. *)
val pool_size : gpu_mba_pool -> int

(** Returns true if the pool was generated by Apple Metal GPU hardware. *)
val is_gpu_backed : gpu_mba_pool -> bool

(** [obfuscate_alu ~pool ~rng ~dst ~src1 ~src2 op]
    transforms an arithmetic/logical VM operation into an opaque Non-Linear MBA
    expression tree derived from GPU-synthesized solution seeds, and lowers it
    into [Vm_ir.Ir.instr list]. *)
val obfuscate_alu :
  pool:gpu_mba_pool ->
  rng:Random.State.t ->
  dst:Register.t ->
  src1:Ir.operand ->
  src2:Ir.operand ->
  Ir.alu_op ->
  Ir.instr list
