/* ========================================================================= */
/*  ASGARD-5877 Polymorphic C/C++ Obfuscation & Hardening Macro Header       */
/*  Auto-generated by Random_vISA / ASGARD-5877 Macro Obfuscation Engine     */
/* ========================================================================= */
#ifndef _ASGARD_OBF_H_
#define _ASGARD_OBF_H_

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#if defined(__GNUC__) || defined(__clang__)
  #define ASG_INLINE __attribute__((always_inline)) inline
#elif defined(_MSC_VER)
  #define ASG_INLINE __forceinline
#else
  #define ASG_INLINE inline
#endif

/* ------------------------------------------------------------------------- */
/* 1. STACK STRING ENCRYPTION (Alloca / Compound Literal Decryption)         */
/* ------------------------------------------------------------------------- */
#if defined(__GNUC__) || defined(__clang__)
#define ASG_STR(enc_bytes, len, key) ({ \
    static const uint8_t _enc[] = enc_bytes; \
    char* _buf = (char*)__builtin_alloca((len) + 1); \
    for (size_t _i = 0; _i < (size_t)(len); ++_i) { \
        uint8_t _k = (uint8_t)(((uint32_t)(key) ^ (uint32_t)(_i * 0x5DU)) & 0xFFU); \
        _buf[_i] = (char)(_enc[_i] ^ _k); \
    } \
    _buf[len] = '\0'; \
    _buf; \
})
#else
static ASG_INLINE char* ASG_decrypt_str(char* buf, const uint8_t* enc, size_t len, uint32_t key) {
    for (size_t i = 0; i < len; ++i) {
        uint8_t k = (uint8_t)((key ^ (uint32_t)(i * 0x5DU)) & 0xFFU);
        buf[i] = (char)(enc[i] ^ k);
    }
    buf[len] = '\0';
    return buf;
}
#define ASG_STR(enc_bytes, len, key) \
    ASG_decrypt_str((char*)alloca((len) + 1), (const uint8_t*)(enc_bytes), (len), (key))
#endif

/* ------------------------------------------------------------------------- */
/* 2. MIXED BOOLEAN-ARITHMETIC (MBA) MACROS (Zhou / Eyrolles Identities)     */
/* ------------------------------------------------------------------------- */
/* Addition: x + y = (x ^ y) + 2*(x & y) */
#define ASG_MBA_ADD(a, b) (((a) ^ (b)) + 2 * ((a) & (b)))

/* Subtraction: x - y = (x ^ y) - 2*(~x & y) */
#define ASG_MBA_SUB(a, b) (((a) ^ (b)) - 2 * ((~(a)) & (b)))

/* Bitwise XOR: x ^ y = (x | y) - (x & y) */
#define ASG_MBA_XOR(a, b) (((a) | (b)) - ((a) & (b)))

/* Bitwise AND: x & y = (x + y) - (x | y) */
#define ASG_MBA_AND(a, b) (((a) + (b)) - ((a) | (b)))

/* Bitwise OR: x | y = (x ^ y) + (x & y) */
#define ASG_MBA_OR(a, b) (((a) ^ (b)) + ((a) & (b)))

/* Bitwise NOT: ~x = x ^ 0xFFFFFFFFFFFFFFFFULL */
#define ASG_MBA_NOT(a) ((a) ^ 0xFFFFFFFFFFFFFFFFULL)

/* Level 2 Nested MBA: x + y expanded through XOR and AND identities */
#define ASG_MBA_ADD_L2(a, b) (ASG_MBA_XOR((a), (b)) + 2 * ASG_MBA_AND((a), (b)))
#define ASG_MBA_SUB_L2(a, b) (ASG_MBA_XOR((a), (b)) - 2 * ASG_MBA_AND(ASG_MBA_NOT(a), (b)))

/* ------------------------------------------------------------------------- */
/* 3. CONSTANT BLINDING MACROS                                              */
/* ------------------------------------------------------------------------- */
#define ASG_BLIND_U64(c1, k1, k2) ((((uint64_t)(c1) ^ (uint64_t)(k1)) + (uint64_t)(k2)) - (uint64_t)(k2))
#define ASG_BLIND_I64(c1, k1, k2) ((int64_t)ASG_BLIND_U64(c1, k1, k2))
#define ASG_BLIND_I32(c1, k1, k2) ((int32_t)ASG_BLIND_U64(c1, k1, k2))

/* ------------------------------------------------------------------------- */
/* 4. NUMBER-THEORETIC OPAQUE PREDICATES                                    */
/* Invariants: for all x in Z, x*(x+1) % 2 == 0 and x^2 + x + 7 % 2 != 0    */
/* ------------------------------------------------------------------------- */
#define ASG_OPAQUE_TRUE(x)  (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) == 0ULL)
#define ASG_OPAQUE_FALSE(x) (((((uint64_t)(x)) * (((uint64_t)(x)) + 1ULL)) % 2ULL) != 0ULL)
#define ASG_IF_OPAQUE(x, true_body, false_body) do { \
    if (ASG_OPAQUE_TRUE(x)) { true_body; } else { false_body; } \
} while(0)

/* ------------------------------------------------------------------------- */
/* 5. CONTROL-FLOW FLATTENING (CFF) PREPROCESSOR DSL                        */
/* ------------------------------------------------------------------------- */
#define ASG_CFF_BEGIN(state_var, init_state) \
    uint32_t state_var = (init_state); \
    while (state_var != 0U) { \
        switch (state_var) {

#define ASG_CFF_STATE(state_id) case (state_id):

#define ASG_CFF_NEXT(state_var, next_state) do { \
    state_var = (next_state); \
} while(0); break

#define ASG_CFF_EXIT(state_var) do { \
    state_var = 0U; \
} while(0); break

#define ASG_CFF_END() \
        default: \
            state_var = 0U; \
            break; \
        } \
    }

/* ------------------------------------------------------------------------- */
/* 6. MARKER-BASED REGION PROTECTION (VMProtect Style SDK)                   */
/* ------------------------------------------------------------------------- */
#if defined(__GNUC__) || defined(__clang__)
  #define ASGARD_BEGIN_VIRTUALIZE(tag) \
      __asm__ volatile (".byte 0xEB, 0x0E, 'A','S','G','A','R','D','_','B','E','G','_','V','_','_' \n\t")
  #define ASGARD_BEGIN_MUTATION(tag) \
      __asm__ volatile (".byte 0xEB, 0x0E, 'A','S','G','A','R','D','_','B','E','G','_','M','_','_' \n\t")
  #define ASGARD_BEGIN_ULTRA(tag) \
      __asm__ volatile (".byte 0xEB, 0x0E, 'A','S','G','A','R','D','_','B','E','G','_','U','_','_' \n\t")
  #define ASGARD_END() \
      __asm__ volatile (".byte 0xEB, 0x0E, 'A','S','G','A','R','D','_','E','N','D','_','_','_','_' \n\t")
#else
  #define ASGARD_BEGIN_VIRTUALIZE(tag)
  #define ASGARD_BEGIN_MUTATION(tag)
  #define ASGARD_BEGIN_ULTRA(tag)
  #define ASGARD_END()
#endif

#endif /* _ASGARD_OBF_H_ */
