let emit_simd_handlers b =
  Buffer.add_string b "    H_VADD_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "#if defined(ASGARD_VECTOR_ISA) && defined(__aarch64__)\n";
  Buffer.add_string b "        uint64x2_t vd = vcombine_u64(vcreate_u64(d0), vcreate_u64(d1));\n";
  Buffer.add_string b "        uint64x2_t vs = vcombine_u64(vcreate_u64(s0), vcreate_u64(s1));\n";
  Buffer.add_string b "        uint64x2_t vr = vaddq_u64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, vgetq_lane_u64(vr, 0), vgetq_lane_u64(vr, 1));\n";
  Buffer.add_string b "#elif defined(ASGARD_VECTOR_ISA) && defined(__x86_64__)\n";
  Buffer.add_string b "        __m128i vd = _mm_set_epi64x((int64_t)d1, (int64_t)d0);\n";
  Buffer.add_string b "        __m128i vs = _mm_set_epi64x((int64_t)s1, (int64_t)s0);\n";
  Buffer.add_string b "        __m128i vr = _mm_add_epi64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, (uint64_t)_mm_extract_epi64(vr, 0), (uint64_t)_mm_extract_epi64(vr, 1));\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 + s0, d1 + s1);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";

  Buffer.add_string b "    H_VSUB_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "#if defined(ASGARD_VECTOR_ISA) && defined(__aarch64__)\n";
  Buffer.add_string b "        uint64x2_t vd = vcombine_u64(vcreate_u64(d0), vcreate_u64(d1));\n";
  Buffer.add_string b "        uint64x2_t vs = vcombine_u64(vcreate_u64(s0), vcreate_u64(s1));\n";
  Buffer.add_string b "        uint64x2_t vr = vsubq_u64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, vgetq_lane_u64(vr, 0), vgetq_lane_u64(vr, 1));\n";
  Buffer.add_string b "#elif defined(ASGARD_VECTOR_ISA) && defined(__x86_64__)\n";
  Buffer.add_string b "        __m128i vd = _mm_set_epi64x((int64_t)d1, (int64_t)d0);\n";
  Buffer.add_string b "        __m128i vs = _mm_set_epi64x((int64_t)s1, (int64_t)s0);\n";
  Buffer.add_string b "        __m128i vr = _mm_sub_epi64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, (uint64_t)_mm_extract_epi64(vr, 0), (uint64_t)_mm_extract_epi64(vr, 1));\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 - s0, d1 - s1);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";

  Buffer.add_string b "    H_VMUL_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 * s0, d1 * s1);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";

  Buffer.add_string b "    H_VXOR_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "#if defined(ASGARD_VECTOR_ISA) && defined(__aarch64__)\n";
  Buffer.add_string b "        uint64x2_t vd = vcombine_u64(vcreate_u64(d0), vcreate_u64(d1));\n";
  Buffer.add_string b "        uint64x2_t vs = vcombine_u64(vcreate_u64(s0), vcreate_u64(s1));\n";
  Buffer.add_string b "        uint64x2_t vr = veorq_u64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, vgetq_lane_u64(vr, 0), vgetq_lane_u64(vr, 1));\n";
  Buffer.add_string b "#elif defined(ASGARD_VECTOR_ISA) && defined(__x86_64__)\n";
  Buffer.add_string b "        __m128i vd = _mm_set_epi64x((int64_t)d1, (int64_t)d0);\n";
  Buffer.add_string b "        __m128i vs = _mm_set_epi64x((int64_t)s1, (int64_t)s0);\n";
  Buffer.add_string b "        __m128i vr = _mm_xor_si128(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, (uint64_t)_mm_extract_epi64(vr, 0), (uint64_t)_mm_extract_epi64(vr, 1));\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 ^ s0, d1 ^ s1);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n";
  Buffer.add_string b "    H_VEC_MOV: {\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)(imm & 0x3ff);\n";
  Buffer.add_string b "        for (size_t i = 0; i < (bits + 63) / 64; ++i) ctx.set_vreg_lane(dst, i, ctx.get_vreg_lane(src, i));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_BINOP: {\n";
  Buffer.add_string b "        uint32_t src2 = (uint32_t)(imm & 31);\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)((imm >> 5) & 0x3ff);\n";
  Buffer.add_string b "        uint32_t lane_bits = (uint32_t)((imm >> 15) & 0xff);\n";
  Buffer.add_string b "        if (lane_bits == 0) lane_bits = 64;\n";
  Buffer.add_string b "        uint32_t vop = (uint32_t)((imm >> 23) & 0x1f);\n";
  Buffer.add_string b "        uint32_t elem = (uint32_t)((imm >> 28) & 0x3);\n";
  Buffer.add_string b "        uint64_t mask = lane_bits == 8 ? 0xffULL : (lane_bits == 16 ? 0xffffULL : (lane_bits == 32 ? 0xffffffffULL : ~0ULL));\n";
  Buffer.add_string b "        for (size_t bit = 0; bit < bits; bit += lane_bits) {\n";
  Buffer.add_string b "            size_t chunk = bit / 64; unsigned shift = (unsigned)(bit % 64);\n";
  Buffer.add_string b "            uint64_t a = (ctx.get_vreg_lane(src, chunk) >> shift) & mask;\n";
  Buffer.add_string b "            uint64_t b = (ctx.get_vreg_lane(src2, chunk) >> shift) & mask;\n";
  Buffer.add_string b "            uint64_t value = 0;\n";
  Buffer.add_string b "            if (elem == 1 && vop <= 2) {\n";
  Buffer.add_string b "                float fa = std::bit_cast<float>(static_cast<uint32_t>(a));\n";
  Buffer.add_string b "                float fb = std::bit_cast<float>(static_cast<uint32_t>(b));\n";
  Buffer.add_string b "                float fr = vop == 0 ? fa + fb : (vop == 1 ? fa - fb : fa * fb);\n";
  Buffer.add_string b "                value = std::bit_cast<uint32_t>(fr);\n";
  Buffer.add_string b "            } else if (elem == 1 && vop == 11) {\n";
  Buffer.add_string b "                float fa = std::bit_cast<float>(static_cast<uint32_t>(a));\n";
  Buffer.add_string b "                float fb = std::bit_cast<float>(static_cast<uint32_t>(b));\n";
  Buffer.add_string b "                value = std::bit_cast<uint32_t>(std::fmin(fa, fb));\n";
  Buffer.add_string b "            } else if (elem == 1 && vop == 12) {\n";
  Buffer.add_string b "                float fa = std::bit_cast<float>(static_cast<uint32_t>(a));\n";
  Buffer.add_string b "                float fb = std::bit_cast<float>(static_cast<uint32_t>(b));\n";
  Buffer.add_string b "                value = std::bit_cast<uint32_t>(std::fmax(fa, fb));\n";
  Buffer.add_string b "            } else if (elem == 2 && vop <= 2) {\n";
  Buffer.add_string b "                double fa = std::bit_cast<double>(a);\n";
  Buffer.add_string b "                double fb = std::bit_cast<double>(b);\n";
  Buffer.add_string b "                double fr = vop == 0 ? fa + fb : (vop == 1 ? fa - fb : fa * fb);\n";
  Buffer.add_string b "                value = std::bit_cast<uint64_t>(fr);\n";
  Buffer.add_string b "            } else if (elem == 2 && vop == 11) {\n";
  Buffer.add_string b "                double fa = std::bit_cast<double>(a);\n";
  Buffer.add_string b "                double fb = std::bit_cast<double>(b);\n";
  Buffer.add_string b "                value = std::bit_cast<uint64_t>(std::fmin(fa, fb));\n";
  Buffer.add_string b "            } else if (elem == 2 && vop == 12) {\n";
  Buffer.add_string b "                double fa = std::bit_cast<double>(a);\n";
  Buffer.add_string b "                double fb = std::bit_cast<double>(b);\n";
  Buffer.add_string b "                value = std::bit_cast<uint64_t>(std::fmax(fa, fb));\n";
  Buffer.add_string b "            } else {\n";
  Buffer.add_string b "                int64_t sa = lane_bits == 8 ? (int64_t)(int8_t)a : (lane_bits == 16 ? (int64_t)(int16_t)a : (lane_bits == 32 ? (int64_t)(int32_t)a : (int64_t)a));\n";
  Buffer.add_string b "                int64_t sb = lane_bits == 8 ? (int64_t)(int8_t)b : (lane_bits == 16 ? (int64_t)(int16_t)b : (lane_bits == 32 ? (int64_t)(int32_t)b : (int64_t)b));\n";
  Buffer.add_string b "                switch (vop) {\n";
  Buffer.add_string b "                    case 0: value = a + b; break;\n";
  Buffer.add_string b "                    case 1: value = a - b; break;\n";
  Buffer.add_string b "                    case 2: value = a * b; break;\n";
  Buffer.add_string b "                    case 3: value = a & b; break;\n";
  Buffer.add_string b "                    case 4: value = a | b; break;\n";
  Buffer.add_string b "                    case 5: value = a ^ b; break;\n";
  Buffer.add_string b "                    case 6: { uint32_t cnt = (uint32_t)(ctx.get_vreg_lane(src2, 0) & 0xff); value = (cnt >= lane_bits) ? 0 : (a << cnt); break; }\n";
  Buffer.add_string b "                    case 7: { uint32_t cnt = (uint32_t)(ctx.get_vreg_lane(src2, 0) & 0xff); value = (cnt >= lane_bits) ? 0 : (a >> cnt); break; }\n";
  Buffer.add_string b "                    case 8: { uint32_t cnt = (uint32_t)(ctx.get_vreg_lane(src2, 0) & 0xff); value = (cnt >= lane_bits) ? (sa < 0 ? mask : 0) : ((uint64_t)(sa >> cnt) & mask); break; }\n";
  Buffer.add_string b "                    case 9: value = (a == b) ? mask : 0; break;\n";
  Buffer.add_string b "                    case 10: value = (sa > sb) ? mask : 0; break;\n";
  Buffer.add_string b "                    case 11: value = (sa < sb) ? a : b; break;\n";
  Buffer.add_string b "                    case 12: value = (sa > sb) ? a : b; break;\n";
  Buffer.add_string b "                    case 13: value = (a < b) ? a : b; break;\n";
  Buffer.add_string b "                    case 14: value = (a > b) ? a : b; break;\n";
  Buffer.add_string b "                    case 15: value = (uint64_t)(sa < 0 ? -sa : sa) & mask; break;\n";
  Buffer.add_string b "                    case 16: value = (~a) & b; break;\n";
  Buffer.add_string b "                    case 17: {\n";
  Buffer.add_string b "                        size_t block_lane = (bit / lane_bits) % (128 / lane_bits);\n";
  Buffer.add_string b "                        size_t half_idx = block_lane / 2;\n";
  Buffer.add_string b "                        size_t src_reg = (block_lane % 2 == 0) ? src : src2;\n";
  Buffer.add_string b "                        size_t src_bit = ((bit / 128) * 128) + (half_idx * lane_bits);\n";
  Buffer.add_string b "                        value = (ctx.get_vreg_lane(src_reg, src_bit / 64) >> (src_bit % 64)) & mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 18: {\n";
  Buffer.add_string b "                        size_t num_lanes = 128 / lane_bits;\n";
  Buffer.add_string b "                        size_t block_lane = (bit / lane_bits) % num_lanes;\n";
  Buffer.add_string b "                        size_t half_idx = (num_lanes / 2) + (block_lane / 2);\n";
  Buffer.add_string b "                        size_t src_reg = (block_lane % 2 == 0) ? src : src2;\n";
  Buffer.add_string b "                        size_t src_bit = ((bit / 128) * 128) + (half_idx * lane_bits);\n";
  Buffer.add_string b "                        value = (ctx.get_vreg_lane(src_reg, src_bit / 64) >> (src_bit % 64)) & mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 21: {\n";
  Buffer.add_string b "                        uint8_t ctrl = (uint8_t)(b & 0xff);\n";
  Buffer.add_string b "                        if (ctrl & 0x80) value = 0;\n";
  Buffer.add_string b "                        else {\n";
  Buffer.add_string b "                            size_t src_bit = ((bit / 128) * 128) + ((ctrl & 0xf) * 8);\n";
  Buffer.add_string b "                            value = (ctx.get_vreg_lane(src, src_bit / 64) >> (src_bit % 64)) & 0xff;\n";
  Buffer.add_string b "                        }\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 23: {\n";
  Buffer.add_string b "                        size_t num_lanes = 128 / lane_bits;\n";
  Buffer.add_string b "                        size_t block_lane = (bit / lane_bits) % num_lanes;\n";
  Buffer.add_string b "                        size_t half_len = num_lanes / 2;\n";
  Buffer.add_string b "                        size_t src_reg = (block_lane < half_len) ? src : src2;\n";
  Buffer.add_string b "                        size_t sel_elem = (block_lane < half_len) ? (block_lane * 2) : ((block_lane - half_len) * 2);\n";
  Buffer.add_string b "                        size_t src_bit = ((bit / 128) * 128) + (sel_elem * lane_bits);\n";
  Buffer.add_string b "                        value = (ctx.get_vreg_lane(src_reg, src_bit / 64) >> (src_bit % 64)) & mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 24: {\n";
  Buffer.add_string b "                        size_t num_lanes = 128 / lane_bits;\n";
  Buffer.add_string b "                        size_t block_lane = (bit / lane_bits) % num_lanes;\n";
  Buffer.add_string b "                        size_t half_len = num_lanes / 2;\n";
  Buffer.add_string b "                        size_t src_reg = (block_lane < half_len) ? src : src2;\n";
  Buffer.add_string b "                        size_t sel_elem = (block_lane < half_len) ? (block_lane * 2 + 1) : ((block_lane - half_len) * 2 + 1);\n";
  Buffer.add_string b "                        size_t src_bit = ((bit / 128) * 128) + (sel_elem * lane_bits);\n";
  Buffer.add_string b "                        value = (ctx.get_vreg_lane(src_reg, src_bit / 64) >> (src_bit % 64)) & mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 25: {\n";
  Buffer.add_string b "                        size_t num_lanes = 128 / lane_bits;\n";
  Buffer.add_string b "                        size_t block_lane = (bit / lane_bits) % num_lanes;\n";
  Buffer.add_string b "                        size_t k = block_lane / 2;\n";
  Buffer.add_string b "                        size_t src_reg = (block_lane % 2 == 0) ? src : src2;\n";
  Buffer.add_string b "                        size_t sel_elem = k * 2;\n";
  Buffer.add_string b "                        size_t src_bit = ((bit / 128) * 128) + (sel_elem * lane_bits);\n";
  Buffer.add_string b "                        value = (ctx.get_vreg_lane(src_reg, src_bit / 64) >> (src_bit % 64)) & mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 26: {\n";
  Buffer.add_string b "                        size_t num_lanes = 128 / lane_bits;\n";
  Buffer.add_string b "                        size_t block_lane = (bit / lane_bits) % num_lanes;\n";
  Buffer.add_string b "                        size_t k = block_lane / 2;\n";
  Buffer.add_string b "                        size_t src_reg = (block_lane % 2 == 0) ? src : src2;\n";
  Buffer.add_string b "                        size_t sel_elem = k * 2 + 1;\n";
  Buffer.add_string b "                        size_t src_bit = ((bit / 128) * 128) + (sel_elem * lane_bits);\n";
  Buffer.add_string b "                        value = (ctx.get_vreg_lane(src_reg, src_bit / 64) >> (src_bit % 64)) & mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 28: {\n";
  Buffer.add_string b "                        uint8_t idx = (uint8_t)(b & 0xff);\n";
  Buffer.add_string b "                        if (idx < 16) {\n";
  Buffer.add_string b "                            size_t src_bit = ((bit / 128) * 128) + (idx * 8);\n";
  Buffer.add_string b "                            value = (ctx.get_vreg_lane(src, src_bit / 64) >> (src_bit % 64)) & 0xff;\n";
  Buffer.add_string b "                        } else {\n";
  Buffer.add_string b "                            value = 0;\n";
  Buffer.add_string b "                        }\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 29: {\n";
  Buffer.add_string b "                        uint8_t idx = (uint8_t)(b & 0xff);\n";
  Buffer.add_string b "                        if (idx < 16) {\n";
  Buffer.add_string b "                            size_t src_bit = ((bit / 128) * 128) + (idx * 8);\n";
  Buffer.add_string b "                            value = (ctx.get_vreg_lane(src, src_bit / 64) >> (src_bit % 64)) & 0xff;\n";
  Buffer.add_string b "                        } else {\n";
  Buffer.add_string b "                            value = (ctx.get_vreg_lane(dst, chunk) >> shift) & 0xff;\n";
  Buffer.add_string b "                        }\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 30: {\n";
  Buffer.add_string b "                        int64_t min_val = (lane_bits == 64) ? (int64_t)0x8000000000000000ULL : (lane_bits == 32) ? (int64_t)(int32_t)0x80000000 : (lane_bits == 16) ? (int64_t)(int16_t)0x8000 : (int64_t)(int8_t)0x80;\n";
  Buffer.add_string b "                        if (sb == 0) value = ~0ULL;\n";
  Buffer.add_string b "                        else if (sb == -1 && sa == min_val) value = (uint64_t)sa;\n";
  Buffer.add_string b "                        else value = (uint64_t)(sa / sb);\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 31: {\n";
  Buffer.add_string b "                        value = (b != 0) ? (a / b) : mask;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 32: {\n";
  Buffer.add_string b "                        int64_t min_val = (lane_bits == 64) ? (int64_t)0x8000000000000000ULL : (lane_bits == 32) ? (int64_t)(int32_t)0x80000000 : (lane_bits == 16) ? (int64_t)(int16_t)0x8000 : (int64_t)(int8_t)0x80;\n";
  Buffer.add_string b "                        if (sb == 0) value = a;\n";
  Buffer.add_string b "                        else if (sb == -1 && sa == min_val) value = 0;\n";
  Buffer.add_string b "                        else value = (uint64_t)(sa % sb);\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 33: {\n";
  Buffer.add_string b "                        value = (b != 0) ? (a % b) : a;\n";
  Buffer.add_string b "                        break;\n";
  Buffer.add_string b "                    }\n";
  Buffer.add_string b "                    case 34: value = (a != b) ? mask : 0; break;\n";
  Buffer.add_string b "                    case 35: value = (sa <= sb) ? mask : 0; break;\n";
  Buffer.add_string b "                    case 36: value = (a < b) ? mask : 0; break;\n";
  Buffer.add_string b "                    case 37: value = (a <= b) ? mask : 0; break;\n";
  Buffer.add_string b "                    default: value = a ^ b; break;\n";
  Buffer.add_string b "                }\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            uint64_t old_value = ctx.get_vreg_lane(dst, chunk);\n";
  Buffer.add_string b "            uint64_t packed_mask = mask << shift;\n";
  Buffer.add_string b "            ctx.set_vreg_lane(dst, chunk, (old_value & ~packed_mask) | ((value & mask) << shift));\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_IMM: {\n";
  Buffer.add_string b "        uint64_t imm_val = imm & 0xffULL;\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)((imm >> 8) & 0x3ff);\n";
  Buffer.add_string b "        uint32_t lane_bits = (uint32_t)((imm >> 18) & 0xff);\n";
  Buffer.add_string b "        if (lane_bits == 0) lane_bits = 64;\n";
  Buffer.add_string b "        uint32_t vop = (uint32_t)((imm >> 26) & 0x1f);\n";
  Buffer.add_string b "        uint64_t mask = lane_bits == 8 ? 0xffULL : (lane_bits == 16 ? 0xffffULL : (lane_bits == 32 ? 0xffffffffULL : ~0ULL));\n";
  Buffer.add_string b "        for (size_t bit = 0; bit < bits; bit += lane_bits) {\n";
  Buffer.add_string b "            size_t chunk = bit / 64; unsigned shift = (unsigned)(bit % 64);\n";
  Buffer.add_string b "            uint64_t a = (ctx.get_vreg_lane(src, chunk) >> shift) & mask;\n";
  Buffer.add_string b "            int64_t sa = lane_bits == 8 ? (int64_t)(int8_t)a : (lane_bits == 16 ? (int64_t)(int16_t)a : (lane_bits == 32 ? (int64_t)(int32_t)a : (int64_t)a));\n";
  Buffer.add_string b "            uint64_t value = 0;\n";
  Buffer.add_string b "            switch (vop) {\n";
  Buffer.add_string b "                case 6: { uint32_t cnt = (uint32_t)imm_val; value = (cnt >= lane_bits) ? 0 : (a << cnt); break; }\n";
  Buffer.add_string b "                case 7: { uint32_t cnt = (uint32_t)imm_val; value = (cnt >= lane_bits) ? 0 : (a >> cnt); break; }\n";
  Buffer.add_string b "                case 8: { uint32_t cnt = (uint32_t)imm_val; value = (cnt >= lane_bits) ? (sa < 0 ? mask : 0) : ((uint64_t)(sa >> cnt) & mask); break; }\n";
  Buffer.add_string b "                case 21: {\n";
  Buffer.add_string b "                    size_t lane_in_128 = (bit / 32) % 4;\n";
  Buffer.add_string b "                    size_t sel = (imm_val >> (lane_in_128 * 2)) & 3;\n";
  Buffer.add_string b "                    size_t src_bit = ((bit / 128) * 128) + (sel * 32);\n";
  Buffer.add_string b "                    value = (ctx.get_vreg_lane(src, src_bit / 64) >> (src_bit % 64)) & 0xffffffffULL;\n";
  Buffer.add_string b "                    break;\n";
  Buffer.add_string b "                }\n";
  Buffer.add_string b "                case 22: {\n";
  Buffer.add_string b "                    size_t lane_idx = bit / lane_bits;\n";
  Buffer.add_string b "                    size_t sel = (imm_val >> (lane_idx % 8)) & 1;\n";
  Buffer.add_string b "                    value = (sel == 0) ? a : ((ctx.get_vreg_lane(dst, chunk) >> shift) & mask);\n";
  Buffer.add_string b "                    break;\n";
  Buffer.add_string b "                }\n";
  Buffer.add_string b "                default: value = a; break;\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            uint64_t old_value = ctx.get_vreg_lane(dst, chunk);\n";
  Buffer.add_string b "            uint64_t packed_mask = mask << shift;\n";
  Buffer.add_string b "            ctx.set_vreg_lane(dst, chunk, (old_value & ~packed_mask) | ((value & mask) << shift));\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_CLEAR_UPPER: {\n";
  Buffer.add_string b "        ctx.set_vreg_lane(dst, 2, 0ULL);\n";
  Buffer.add_string b "        ctx.set_vreg_lane(dst, 3, 0ULL);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_ZERO_UPPER: {\n";
  Buffer.add_string b "        for (size_t i = 0; i < 16; ++i) {\n";
  Buffer.add_string b "            ctx.set_vreg_lane(i, 2, 0ULL);\n";
  Buffer.add_string b "            ctx.set_vreg_lane(i, 3, 0ULL);\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_PMOVMSKB: {\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)(imm & 0x3ff);\n";
  Buffer.add_string b "        uint32_t num_bytes = bits / 8;\n";
  Buffer.add_string b "        uint64_t mask = 0;\n";
  Buffer.add_string b "        for (uint32_t b = 0; b < num_bytes; ++b) {\n";
  Buffer.add_string b "            uint64_t byte_val = (ctx.get_vreg_lane(src, b / 8) >> ((b % 8) * 8)) & 0xff;\n";
  Buffer.add_string b "            if (byte_val & 0x80) mask |= (1ULL << b);\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.set_reg(dst, mask);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_LOAD: {\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)((word >> 50) & 0x3ff);\n";
  Buffer.add_string b "        uint64_t address = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        for (size_t i = 0; i < (bits + 63) / 64; ++i) { uint64_t value = 0; std::memcpy(&value, reinterpret_cast<const void*>(address + i * 8), sizeof(value)); ctx.set_vreg_lane(dst, i, value); }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_STORE: {\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)((word >> 50) & 0x3ff);\n";
  Buffer.add_string b "        uint64_t address = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        for (size_t i = 0; i < (bits + 63) / 64; ++i) std::memcpy(reinterpret_cast<void*>(address + i * 8), &ctx.vregs[src & 31][i & 7], sizeof(uint64_t));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_SPLAT: {\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)(imm & 0xffff);\n";
  Buffer.add_string b "        uint32_t lane_bits = (uint32_t)((imm >> 16) & 0xffff);\n";
  Buffer.add_string b "        uint64_t val = ctx.get_reg(src);\n";
  Buffer.add_string b "        uint64_t mask = (lane_bits >= 64) ? ~0ULL : ((1ULL << lane_bits) - 1ULL);\n";
  Buffer.add_string b "        uint64_t val_masked = val & mask;\n";
  Buffer.add_string b "        uint32_t num_lanes = (lane_bits > 0) ? (bits / lane_bits) : 0;\n";
  Buffer.add_string b "        for (uint32_t l = 0; l < num_lanes; ++l) {\n";
  Buffer.add_string b "            uint32_t pos = l * lane_bits;\n";
  Buffer.add_string b "            uint32_t chunk = pos / 64;\n";
  Buffer.add_string b "            uint32_t shift = pos % 64;\n";
  Buffer.add_string b "            uint64_t packed_mask = (lane_bits >= 64) ? ~0ULL : (mask << shift);\n";
  Buffer.add_string b "            uint64_t cur = ctx.get_vreg_lane(dst, chunk);\n";
  Buffer.add_string b "            cur = (cur & ~packed_mask) | (val_masked << shift);\n";
  Buffer.add_string b "            ctx.set_vreg_lane(dst, chunk, cur);\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_VEC_EXT: {\n";
  Buffer.add_string b "        uint32_t src2 = (uint32_t)(imm & 31);\n";
  Buffer.add_string b "        uint32_t shift_bytes = (uint32_t)((imm >> 5) & 15);\n";
  Buffer.add_string b "        uint32_t bits = (uint32_t)((imm >> 9) & 0x3ff);\n";
  Buffer.add_string b "        if (bits == 0) bits = 128;\n";
  Buffer.add_string b "        for (size_t byte_idx = 0; byte_idx < (bits / 8); ++byte_idx) {\n";
  Buffer.add_string b "            size_t total_idx = (byte_idx % 16) + shift_bytes;\n";
  Buffer.add_string b "            uint64_t val = 0;\n";
  Buffer.add_string b "            if (total_idx < 16) {\n";
  Buffer.add_string b "                size_t bit_pos = ((byte_idx / 16) * 128) + (total_idx * 8);\n";
  Buffer.add_string b "                val = (ctx.get_vreg_lane(src, bit_pos / 64) >> (bit_pos % 64)) & 0xff;\n";
  Buffer.add_string b "            } else {\n";
  Buffer.add_string b "                size_t m_idx = total_idx - 16;\n";
  Buffer.add_string b "                size_t bit_pos = ((byte_idx / 16) * 128) + (m_idx * 8);\n";
  Buffer.add_string b "                val = (ctx.get_vreg_lane(src2, bit_pos / 64) >> (bit_pos % 64)) & 0xff;\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            size_t chunk = (byte_idx * 8) / 64; unsigned shift = (unsigned)((byte_idx * 8) % 64);\n";
  Buffer.add_string b "            uint64_t old_v = ctx.get_vreg_lane(dst, chunk);\n";
  Buffer.add_string b "            uint64_t clr = old_v & ~(0xffULL << shift);\n";
  Buffer.add_string b "            ctx.set_vreg_lane(dst, chunk, clr | (val << shift));\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n"

let emit_mem_and_ffi_handlers b =
  Buffer.add_string b "    H_CALL_EXTERN: {\n";
  Buffer.add_string b "        size_t sym_idx = (size_t)imm;\n";
  Buffer.add_string b "        if (sym_idx < sizeof(g_external_symbols) / sizeof(g_external_symbols[0]) && g_external_symbols[sym_idx][0] != '\\0') {\n";
  Buffer.add_string b "            const char* sym_name = g_external_symbols[sym_idx];\n";
  Buffer.add_string b "            void* sym_ptr = dlsym(RTLD_DEFAULT, sym_name);\n";
  Buffer.add_string b "            if (!sym_ptr && sym_name[0] == '_') sym_ptr = dlsym(RTLD_DEFAULT, sym_name + 1);\n";
  Buffer.add_string b "            if (!sym_ptr) {\n";
  Buffer.add_string b "                char alt_name[256];\n";
  Buffer.add_string b "                snprintf(alt_name, sizeof(alt_name), \"_%s\", sym_name);\n";
  Buffer.add_string b "                sym_ptr = dlsym(RTLD_DEFAULT, alt_name);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            if (sym_ptr) {\n";
  Buffer.add_string b "                const char* clean_name = (sym_name[0] == '_') ? sym_name + 1 : sym_name;\n";
  Buffer.add_string b "                uint64_t a0 = ctx.get_reg(REG_RAX);\n";
  Buffer.add_string b "                uint64_t a1 = ctx.get_reg(REG_RCX);\n";
  Buffer.add_string b "                uint64_t a2 = ctx.get_reg(REG_RDX);\n";
  Buffer.add_string b "                uint64_t a3 = ctx.get_reg(REG_RBX);\n";
  Buffer.add_string b "                uint64_t a4 = ctx.get_reg(REG_RSI);\n";
  Buffer.add_string b "                uint64_t a5 = ctx.get_reg(REG_RDI);\n";
  Buffer.add_string b "                uint64_t a6 = ctx.get_reg(REG_R8);\n";
  Buffer.add_string b "                uint64_t a7 = ctx.get_reg(REG_R9);\n";
  Buffer.add_string b "                const uint64_t* stk = reinterpret_cast<const uint64_t*>(ctx.get_reg(REG_RSP));\n";
  Buffer.add_string b "                uint64_t ret_val = 0;\n";
  Buffer.add_string b "                if (strcmp(clean_name, \"printf\") == 0) {\n";
  Buffer.add_string b "                    typedef int (*printf_fn_t)(const char*, ...);\n";
  Buffer.add_string b "                    printf_fn_t pfn = reinterpret_cast<printf_fn_t>(sym_ptr);\n";
  Buffer.add_string b "#if defined(__APPLE__) && defined(__aarch64__)\n";
  Buffer.add_string b "                    ret_val = (uint64_t)pfn((const char*)a0, stk[0], stk[1], stk[2], stk[3], stk[4], stk[5], stk[6], stk[7]);\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "                    ret_val = (uint64_t)pfn((const char*)a0, a1, a2, a3, a4, a5, a6, a7);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "                } else if (strcmp(clean_name, \"fprintf\") == 0 || strcmp(clean_name, \"dprintf\") == 0) {\n";
  Buffer.add_string b "                    typedef int (*fprintf_fn_t)(void*, const char*, ...);\n";
  Buffer.add_string b "                    fprintf_fn_t fpfn = reinterpret_cast<fprintf_fn_t>(sym_ptr);\n";
  Buffer.add_string b "#if defined(__APPLE__) && defined(__aarch64__)\n";
  Buffer.add_string b "                    ret_val = (uint64_t)fpfn((void*)a0, (const char*)a1, stk[0], stk[1], stk[2], stk[3], stk[4], stk[5], stk[6], stk[7]);\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "                    ret_val = (uint64_t)fpfn((void*)a0, (const char*)a1, a2, a3, a4, a5, a6, a7);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "                } else if (strcmp(clean_name, \"sprintf\") == 0) {\n";
  Buffer.add_string b "                    typedef int (*sprintf_fn_t)(char*, const char*, ...);\n";
  Buffer.add_string b "                    sprintf_fn_t spfn = reinterpret_cast<sprintf_fn_t>(sym_ptr);\n";
  Buffer.add_string b "#if defined(__APPLE__) && defined(__aarch64__)\n";
  Buffer.add_string b "                    ret_val = (uint64_t)spfn((char*)a0, (const char*)a1, stk[0], stk[1], stk[2], stk[3], stk[4], stk[5], stk[6], stk[7]);\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "                    ret_val = (uint64_t)spfn((char*)a0, (const char*)a1, a2, a3, a4, a5, a6, a7);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "                } else if (strcmp(clean_name, \"snprintf\") == 0) {\n";
  Buffer.add_string b "                    typedef int (*snprintf_fn_t)(char*, size_t, const char*, ...);\n";
  Buffer.add_string b "                    snprintf_fn_t snpfn = reinterpret_cast<snprintf_fn_t>(sym_ptr);\n";
  Buffer.add_string b "#if defined(__APPLE__) && defined(__aarch64__)\n";
  Buffer.add_string b "                    ret_val = (uint64_t)snpfn((char*)a0, (size_t)a1, (const char*)a2, stk[0], stk[1], stk[2], stk[3], stk[4], stk[5], stk[6], stk[7]);\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "                    ret_val = (uint64_t)snpfn((char*)a0, (size_t)a1, (const char*)a2, a3, a4, a5, a6, a7);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "                } else {\n";
  Buffer.add_string b "                    typedef uint64_t (*extern_fn_t)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);\n";
  Buffer.add_string b "                    extern_fn_t fn = reinterpret_cast<extern_fn_t>(sym_ptr);\n";
  Buffer.add_string b "                    ret_val = fn(a0, a1, a2, a3, a4, a5, a6, a7);\n";
  Buffer.add_string b "                }\n";
  Buffer.add_string b "                ctx.set_reg(REG_RAX, ret_val);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n";

  Buffer.add_string b "    H_LOAD_64: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, *reinterpret_cast<const uint64_t*>(addr));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_32: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(*reinterpret_cast<const uint32_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_16: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(*reinterpret_cast<const uint16_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_8: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(*reinterpret_cast<const uint8_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_S32: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(int64_t)(*reinterpret_cast<const int32_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_S16: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(int64_t)(*reinterpret_cast<const int16_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_S8: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(int64_t)(*reinterpret_cast<const int8_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_64: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint64_t*>(addr) = ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_32: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint32_t*>(addr) = (uint32_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_16: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint16_t*>(addr) = (uint16_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_8: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint8_t*>(addr) = (uint8_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_RESOLVE_SYM: {\n";
  Buffer.add_string b "        size_t sym_idx = (size_t)imm;\n";
  Buffer.add_string b "        void* sym_ptr = nullptr;\n";
  Buffer.add_string b "        if (sym_idx < sizeof(g_external_symbols) / sizeof(g_external_symbols[0]) && g_external_symbols[sym_idx][0] != '\\0') {\n";
  Buffer.add_string b "            const char* sym_name = g_external_symbols[sym_idx];\n";
  Buffer.add_string b "            sym_ptr = dlsym(RTLD_DEFAULT, sym_name);\n";
  Buffer.add_string b "            if (!sym_ptr && sym_name[0] == '_') sym_ptr = dlsym(RTLD_DEFAULT, sym_name + 1);\n";
  Buffer.add_string b "            if (!sym_ptr) {\n";
  Buffer.add_string b "                char alt_name[256];\n";
  Buffer.add_string b "                snprintf(alt_name, sizeof(alt_name), \"_%s\", sym_name);\n";
  Buffer.add_string b "                sym_ptr = dlsym(RTLD_DEFAULT, alt_name);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            if (!sym_ptr) {\n";
  Buffer.add_string b "                sym_ptr = asgard_resolve_constant(sym_name);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)sym_ptr);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FADD_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0), b_raw = ctx.get_vreg_lane((uint8_t)imm, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(a + b), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FSUB_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0), b_raw = ctx.get_vreg_lane((uint8_t)imm, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(a - b), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FMUL_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0), b_raw = ctx.get_vreg_lane((uint8_t)imm, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(a * b), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FDIV_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0), b_raw = ctx.get_vreg_lane((uint8_t)imm, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        double r = (b != 0.0) ? (a / b) : 0.0;\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(r), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FSQRT_D: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw);\n";
  Buffer.add_string b "        double r = (a >= 0.0) ? std::sqrt(a) : 0.0;\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(r), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCMP_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0), b_raw = ctx.get_vreg_lane((uint8_t)imm, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.zf = (a == b);\n";
  Buffer.add_string b "        ctx.cf = (a >= b);\n";
  Buffer.add_string b "        ctx.sf = (a < b);\n";
  Buffer.add_string b "        ctx.of = false;\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCVTZS: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw);\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)((int64_t)a));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_SCVTF: {\n";
  Buffer.add_string b "        int64_t v = (int64_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>((double)v), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCVTZU: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw);\n";
  Buffer.add_string b "        ctx.set_reg(dst, (a < 0.0) ? 0ULL : (uint64_t)a);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_UCVTF: {\n";
  Buffer.add_string b "        uint64_t v = ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>((double)v), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCVT: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        float f32 = std::bit_cast<float>((uint32_t)a_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>((double)f32), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_LOAD: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        ctx.set_reg(dst, ptr->load(std::memory_order_seq_cst));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_STORE: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        ptr->store(ctx.get_reg(src), std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_CAS: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        uint64_t expected = ctx.get_reg(src);\n";
  Buffer.add_string b "        uint64_t desired = ctx.get_reg(REG_RAX);\n";
  Buffer.add_string b "        ptr->compare_exchange_strong(expected, desired, std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.set_reg(src, expected);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_ADD: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        uint64_t old = ptr->fetch_add(ctx.get_reg(src), std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.set_reg(src, old);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_SWP: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        uint64_t old = ptr->exchange(ctx.get_reg(src), std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.set_reg(src, old);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_MOV_VR: {\n";
  Buffer.add_string b "        ctx.set_vreg_lane(dst, 0, ctx.get_reg(src));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_MOV_RV: {\n";
  Buffer.add_string b "        ctx.set_reg(dst, ctx.get_vreg_lane(src, 0));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCSEL_VV: {\n";
  Buffer.add_string b "        uint8_t cond = (uint8_t)((word >> 18) & 0x0F);\n";
  Buffer.add_string b "        if (eval_condition(ctx, cond)) ctx.set_vreg_lane(dst, 0, ctx.get_vreg_lane(src, 0));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n"

let emit_decoy_handlers b =
  Buffer.add_string b "    H_DECOY_0: { ctx.set_reg(dst, ctx.get_reg(dst) ^ 0x5877ULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_1: { ctx.set_reg(dst, ctx.get_reg(dst) + (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_2: { ctx.set_reg(dst, ctx.get_reg(dst) * 0x9E37ULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_3: { ctx.set_reg(dst, (ctx.get_reg(dst) << 3) | (ctx.get_reg(dst) >> 61)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_4: { ctx.set_reg(dst, ctx.get_reg(src) ^ (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_5: { ctx.set_reg(dst, ctx.get_reg(dst) & ~ctx.get_reg(src)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_6: { ctx.set_reg(dst, ctx.get_reg(dst) | 0xCAFEBABEULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_7: { ctx.set_reg(dst, (ctx.get_reg(dst) >> 5) ^ (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_8: { ctx.set_reg(dst, ctx.get_reg(dst) - 0x1337ULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_9: { ctx.set_reg(dst, ctx.get_reg(dst) ^ (ctx.get_reg(src) + 1)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_10: { ctx.set_reg(dst, (ctx.get_reg(dst) * 6364136223846793005ULL) + 1); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_11: { ctx.set_reg(dst, (ctx.get_reg(dst) << 7) ^ (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_12: { ctx.set_reg(dst, ctx.get_reg(dst) ^ 0xDEADBEEFULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_13: { ctx.set_reg(dst, ctx.get_reg(dst) + ctx.get_reg(src)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_14: { ctx.set_reg(dst, ctx.get_reg(dst) ^ (uint64_t)(imm * 3)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_15: { ctx.set_reg(dst, ~ctx.get_reg(dst)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY:\n";
  Buffer.add_string b "        ctx.trapped = true;\n";
  Buffer.add_string b "        goto EXIT_VM;\n\n"
