let emit_simd_handlers b =
  Buffer.add_string b "    H_VADD_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "#if defined(ASGARD_VECTOR_ISA) && defined(__aarch64__)\n";
  Buffer.add_string b "        uint64x2_t vd = vcombine_u64(vcreate_u64(d0), vcreate_u64(d1));\n";
  Buffer.add_string b "        uint64x2_t vs = vcombine_u64(vcreate_u64(s0), vcreate_u64(s1));\n";
  Buffer.add_string b "        uint64x2_t vr = vaddq_u64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, vgetq_lane_u64(vr, 0), vgetq_lane_u64(vr, 1));\n";
  Buffer.add_string b "#elif defined(ASGARD_VECTOR_ISA) && defined(__x86_64__)\n";
  Buffer.add_string b "        __m128i vd = _mm_set_epi64x((int64_t)d1, (int64_t)d0);\n";
  Buffer.add_string b "        __m128i vs = _mm_set_epi64x((int64_t)s1, (int64_t)s0);\n";
  Buffer.add_string b "        __m128i vr = _mm_add_epi64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, (uint64_t)_mm_extract_epi64(vr, 0), (uint64_t)_mm_extract_epi64(vr, 1));\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 + s0, d1 + s1);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";

  Buffer.add_string b "    H_VSUB_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "#if defined(ASGARD_VECTOR_ISA) && defined(__aarch64__)\n";
  Buffer.add_string b "        uint64x2_t vd = vcombine_u64(vcreate_u64(d0), vcreate_u64(d1));\n";
  Buffer.add_string b "        uint64x2_t vs = vcombine_u64(vcreate_u64(s0), vcreate_u64(s1));\n";
  Buffer.add_string b "        uint64x2_t vr = vsubq_u64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, vgetq_lane_u64(vr, 0), vgetq_lane_u64(vr, 1));\n";
  Buffer.add_string b "#elif defined(ASGARD_VECTOR_ISA) && defined(__x86_64__)\n";
  Buffer.add_string b "        __m128i vd = _mm_set_epi64x((int64_t)d1, (int64_t)d0);\n";
  Buffer.add_string b "        __m128i vs = _mm_set_epi64x((int64_t)s1, (int64_t)s0);\n";
  Buffer.add_string b "        __m128i vr = _mm_sub_epi64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, (uint64_t)_mm_extract_epi64(vr, 0), (uint64_t)_mm_extract_epi64(vr, 1));\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 - s0, d1 - s1);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";

  Buffer.add_string b "    H_VMUL_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 * s0, d1 * s1);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";

  Buffer.add_string b "    H_VXOR_VV: {\n";
  Buffer.add_string b "        uint64_t d0 = ctx.get_vreg_lane(dst, 0), d1 = ctx.get_vreg_lane(dst, 1);\n";
  Buffer.add_string b "        uint64_t s0 = ctx.get_vreg_lane(src, 0), s1 = ctx.get_vreg_lane(src, 1);\n";
  Buffer.add_string b "#if defined(ASGARD_VECTOR_ISA) && defined(__aarch64__)\n";
  Buffer.add_string b "        uint64x2_t vd = vcombine_u64(vcreate_u64(d0), vcreate_u64(d1));\n";
  Buffer.add_string b "        uint64x2_t vs = vcombine_u64(vcreate_u64(s0), vcreate_u64(s1));\n";
  Buffer.add_string b "        uint64x2_t vr = veorq_u64(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, vgetq_lane_u64(vr, 0), vgetq_lane_u64(vr, 1));\n";
  Buffer.add_string b "#elif defined(ASGARD_VECTOR_ISA) && defined(__x86_64__)\n";
  Buffer.add_string b "        __m128i vd = _mm_set_epi64x((int64_t)d1, (int64_t)d0);\n";
  Buffer.add_string b "        __m128i vs = _mm_set_epi64x((int64_t)s1, (int64_t)s0);\n";
  Buffer.add_string b "        __m128i vr = _mm_xor_si128(vd, vs);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, (uint64_t)_mm_extract_epi64(vr, 0), (uint64_t)_mm_extract_epi64(vr, 1));\n";
  Buffer.add_string b "#else\n";
  Buffer.add_string b "        ctx.set_vreg(dst, d0 ^ s0, d1 ^ s1);\n";
  Buffer.add_string b "#endif\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n"

let emit_mem_and_ffi_handlers b =
  Buffer.add_string b "    H_CALL_EXTERN: {\n";
  Buffer.add_string b "        size_t sym_idx = (size_t)imm;\n";
  Buffer.add_string b "        if (sym_idx < sizeof(g_external_symbols) / sizeof(g_external_symbols[0]) && g_external_symbols[sym_idx][0] != '\\0') {\n";
  Buffer.add_string b "            const char* sym_name = g_external_symbols[sym_idx];\n";
  Buffer.add_string b "            void* sym_ptr = dlsym(RTLD_DEFAULT, sym_name);\n";
  Buffer.add_string b "            if (!sym_ptr && sym_name[0] == '_') sym_ptr = dlsym(RTLD_DEFAULT, sym_name + 1);\n";
  Buffer.add_string b "            if (!sym_ptr) {\n";
  Buffer.add_string b "                char alt_name[256];\n";
  Buffer.add_string b "                snprintf(alt_name, sizeof(alt_name), \"_%s\", sym_name);\n";
  Buffer.add_string b "                sym_ptr = dlsym(RTLD_DEFAULT, alt_name);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            if (sym_ptr) {\n";
  Buffer.add_string b "                typedef uint64_t (*extern_fn_t)(uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);\n";
  Buffer.add_string b "                extern_fn_t fn = reinterpret_cast<extern_fn_t>(sym_ptr);\n";
  Buffer.add_string b "                uint64_t a0 = ctx.get_reg(REG_RAX);\n";
  Buffer.add_string b "                uint64_t a1 = ctx.get_reg(REG_RCX);\n";
  Buffer.add_string b "                uint64_t a2 = ctx.get_reg(REG_RDX);\n";
  Buffer.add_string b "                uint64_t a3 = ctx.get_reg(REG_RBX);\n";
  Buffer.add_string b "                uint64_t a4 = ctx.get_reg(REG_RSI);\n";
  Buffer.add_string b "                uint64_t a5 = ctx.get_reg(REG_RDI);\n";
  Buffer.add_string b "                uint64_t a6 = ctx.get_reg(REG_R8);\n";
  Buffer.add_string b "                uint64_t a7 = ctx.get_reg(REG_R9);\n";
  Buffer.add_string b "                uint64_t ret_val = fn(a0, a1, a2, a3, a4, a5, a6, a7);\n";
  Buffer.add_string b "                ctx.set_reg(REG_RAX, ret_val);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n";

  Buffer.add_string b "    H_LOAD_64: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, *reinterpret_cast<const uint64_t*>(addr));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_32: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(*reinterpret_cast<const uint32_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_16: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(*reinterpret_cast<const uint16_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_8: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(*reinterpret_cast<const uint8_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_S32: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(int64_t)(*reinterpret_cast<const int32_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_S16: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(int64_t)(*reinterpret_cast<const int16_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_LOAD_S8: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)(int64_t)(*reinterpret_cast<const int8_t*>(addr)));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_64: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint64_t*>(addr) = ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_32: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint32_t*>(addr) = (uint32_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_16: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint16_t*>(addr) = (uint16_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_STORE_8: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        *reinterpret_cast<uint8_t*>(addr) = (uint8_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_RESOLVE_SYM: {\n";
  Buffer.add_string b "        size_t sym_idx = (size_t)imm;\n";
  Buffer.add_string b "        void* sym_ptr = nullptr;\n";
  Buffer.add_string b "        if (sym_idx < sizeof(g_external_symbols) / sizeof(g_external_symbols[0]) && g_external_symbols[sym_idx][0] != '\\0') {\n";
  Buffer.add_string b "            const char* sym_name = g_external_symbols[sym_idx];\n";
  Buffer.add_string b "            sym_ptr = dlsym(RTLD_DEFAULT, sym_name);\n";
  Buffer.add_string b "            if (!sym_ptr && sym_name[0] == '_') sym_ptr = dlsym(RTLD_DEFAULT, sym_name + 1);\n";
  Buffer.add_string b "            if (!sym_ptr) {\n";
  Buffer.add_string b "                char alt_name[256];\n";
  Buffer.add_string b "                snprintf(alt_name, sizeof(alt_name), \"_%s\", sym_name);\n";
  Buffer.add_string b "                sym_ptr = dlsym(RTLD_DEFAULT, alt_name);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "            if (!sym_ptr) {\n";
  Buffer.add_string b "                sym_ptr = asgard_resolve_constant(sym_name);\n";
  Buffer.add_string b "            }\n";
  Buffer.add_string b "        }\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)sym_ptr);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FADD_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(dst, 0), b_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(a + b), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FSUB_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(dst, 0), b_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(a - b), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FMUL_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(dst, 0), b_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(a * b), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FDIV_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(dst, 0), b_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        double r = (b != 0.0) ? (a / b) : 0.0;\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>(r), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCMP_DD: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0), b_raw = ctx.get_vreg_lane((uint8_t)imm, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw), b = std::bit_cast<double>(b_raw);\n";
  Buffer.add_string b "        ctx.zf = (a == b);\n";
  Buffer.add_string b "        ctx.cf = (a >= b);\n";
  Buffer.add_string b "        ctx.sf = (a < b);\n";
  Buffer.add_string b "        ctx.of = false;\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_FCVTZS: {\n";
  Buffer.add_string b "        uint64_t a_raw = ctx.get_vreg_lane(src, 0);\n";
  Buffer.add_string b "        double a = std::bit_cast<double>(a_raw);\n";
  Buffer.add_string b "        ctx.set_reg(dst, (uint64_t)((int64_t)a));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_SCVTF: {\n";
  Buffer.add_string b "        int64_t v = (int64_t)ctx.get_reg(src);\n";
  Buffer.add_string b "        ctx.set_vreg(dst, std::bit_cast<uint64_t>((double)v), 0);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_LOAD: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(src) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        ctx.set_reg(dst, ptr->load(std::memory_order_seq_cst));\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_STORE: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        ptr->store(ctx.get_reg(src), std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_CAS: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        uint64_t expected = ctx.get_reg(src);\n";
  Buffer.add_string b "        uint64_t desired = ctx.get_reg(REG_RAX);\n";
  Buffer.add_string b "        ptr->compare_exchange_strong(expected, desired, std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.set_reg(src, expected);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_ADD: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        uint64_t old = ptr->fetch_add(ctx.get_reg(src), std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.set_reg(src, old);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n";
  Buffer.add_string b "    H_ATOMIC_SWP: {\n";
  Buffer.add_string b "        uint64_t addr = ctx.get_reg(dst) + (uint64_t)imm;\n";
  Buffer.add_string b "        auto* ptr = reinterpret_cast<std::atomic<uint64_t>*>(addr);\n";
  Buffer.add_string b "        uint64_t old = ptr->exchange(ctx.get_reg(src), std::memory_order_seq_cst);\n";
  Buffer.add_string b "        ctx.set_reg(src, old);\n";
  Buffer.add_string b "        ctx.executed_instructions++; FETCH_NEXT();\n";
  Buffer.add_string b "    }\n\n"

let emit_decoy_handlers b =
  Buffer.add_string b "    H_DECOY_0: { ctx.set_reg(dst, ctx.get_reg(dst) ^ 0x5877ULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_1: { ctx.set_reg(dst, ctx.get_reg(dst) + (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_2: { ctx.set_reg(dst, ctx.get_reg(dst) * 0x9E37ULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_3: { ctx.set_reg(dst, (ctx.get_reg(dst) << 3) | (ctx.get_reg(dst) >> 61)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_4: { ctx.set_reg(dst, ctx.get_reg(src) ^ (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_5: { ctx.set_reg(dst, ctx.get_reg(dst) & ~ctx.get_reg(src)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_6: { ctx.set_reg(dst, ctx.get_reg(dst) | 0xCAFEBABEULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_7: { ctx.set_reg(dst, (ctx.get_reg(dst) >> 5) ^ (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_8: { ctx.set_reg(dst, ctx.get_reg(dst) - 0x1337ULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_9: { ctx.set_reg(dst, ctx.get_reg(dst) ^ (ctx.get_reg(src) + 1)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_10: { ctx.set_reg(dst, (ctx.get_reg(dst) * 6364136223846793005ULL) + 1); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_11: { ctx.set_reg(dst, (ctx.get_reg(dst) << 7) ^ (uint64_t)imm); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_12: { ctx.set_reg(dst, ctx.get_reg(dst) ^ 0xDEADBEEFULL); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_13: { ctx.set_reg(dst, ctx.get_reg(dst) + ctx.get_reg(src)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_14: { ctx.set_reg(dst, ctx.get_reg(dst) ^ (uint64_t)(imm * 3)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY_15: { ctx.set_reg(dst, ~ctx.get_reg(dst)); ctx.executed_instructions++; FETCH_NEXT(); }\n";
  Buffer.add_string b "    H_DECOY:\n";
  Buffer.add_string b "        ctx.trapped = true;\n";
  Buffer.add_string b "        goto EXIT_VM;\n\n"
